'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const D=require('../portal/domain'),P=require('../portal/passwords'),{createPortal}=require('../portal/app'),{createStore}=require('../portal/store'),{verifyIdentity}=require('../portal/oauth');
const password='Dies ist mein sicherer Test Merksatz!';
async function harness(config={}){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'ux-auth4-')),env={NODE_ENV:'test',PORTAL_LOCAL_DB:path.join(dir,'test.sqlite'),PORTAL_ORIGIN:'http://localhost',PORTAL_TRUST_PROXY:'true',...config};const messages=[];let fail=false;const mail={ready:true,send:async(to,subject,text,attachments,html,messageId)=>{if(fail)throw Error('TEST_SMTP_UNCERTAIN');messages.push({to,subject,text,html,messageId});}};const store=await createStore(env),portal=createPortal({env,store,mail});await portal.ready();const server=http.createServer((req,res)=>portal.handle(req,res,{}));await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;let n=0;
 async function call(route,data,actor={},more={}){const res=await fetch(base+'/api/portal'+route,{method:data===undefined?'GET':'POST',headers:{Origin:env.PORTAL_ORIGIN,'Content-Type':'application/json','X-Forwarded-For':'test-'+(++n),...(actor.cookie?{Cookie:actor.cookie,'X-CSRF-Token':actor.csrf||''}:{}),...(more.headers||{})},body:data===undefined?undefined:JSON.stringify(data),redirect:'manual'});return {status:res.status,json:res.headers.get('content-type')?.includes('json')?await res.json():{},cookie:res.headers.get('set-cookie'),location:res.headers.get('location')};}
 async function actor(response){assert.equal(response.status,200,JSON.stringify(response.json));const a={cookie:response.cookie.split(';')[0]};const me=await call('/me',undefined,a);return {...a,csrf:me.json.csrf,user:me.json.user,company:me.json.company};}
 async function register(email,extra={}){const r=await call('/register-customer',{email,name:'Testkunde',phone:'030123456',privacy:true,terms:true,password,...extra});assert.equal(r.status,200,JSON.stringify(r.json));const token=messages.findLast(m=>m.to===email).text.match(/#token=([a-f0-9]+)/)[1];return actor(await call('/exchange',{token,password}));}
 async function admin(){await call('/login',{email:'info@unfallx.com'});const token=messages.findLast(m=>m.to==='info@unfallx.com').text.match(/#token=([a-f0-9]+)/)[1];return actor(await call('/exchange',{token}));}
 async function drain(){for(let i=0;i<100;i++){const rows=await store.transaction(s=>s.list('notification'));if(!rows.some(r=>['pending','sending'].includes(r.state)))return;await new Promise(r=>setTimeout(r,10));}assert.fail('outbox did not drain');}
 return {env,store,portal,base,call,actor,register,admin,messages,drain,fail(value){fail=value;},async close(){await drain();await new Promise(r=>server.close(r));await portal.close();fs.rmSync(dir,{recursive:true,force:true});}};}
test('Password verification, migration, reset replay and secret redaction over real HTTP',async t=>{const h=await harness();const {call,store,messages}=h;try{
 const data={email:'new@example.com',name:'Test',phone:'123',privacy:true,terms:true,password};
 assert.equal((await call('/register-customer',{...data,password:'short'})).status,400);assert.equal((await call('/register-customer',{...data,terms:false})).status,400);
 await call('/register-customer',data);const token=messages.at(-1).text.match(/#token=([a-f0-9]+)/)[1];assert.equal((await call('/password-login',{email:data.email,password})).status,401);assert.equal((await call('/exchange',{token})).status,401);assert.equal((await call('/exchange',{token,password:'wrong'})).status,401);
 const customer=await h.actor(await call('/exchange',{token,password}));assert.equal(customer.user.hasPassword,true);assert.equal((await call('/exchange',{token,password})).status,401);
 const persisted=await store.transaction(s=>s.get('user',customer.user.id));assert.match(persisted.passwordHash,/^scrypt-v1\$/);assert.ok(!JSON.stringify(persisted).includes(password));assert.equal(customer.user.passwordHash,undefined);
 assert.equal((await call('/password-login',{email:data.email,password:'incorrect'})).status,401);const second=await h.actor(await call('/password-login',{email:data.email,password}));
 for(const route of ['/me','/export','/settings'])assert.ok(!JSON.stringify((await call(route,undefined,customer)).json).includes('scrypt-v1'));
 // Re-registering an existing account must not overwrite its password.
 await call('/register-customer',{...data,password:'Anderer ausreichend langer Test Merksatz!'});assert.equal((await call('/password-login',{email:data.email,password})).status,200);
 await call('/password/request',{email:data.email});const reset=messages.findLast(m=>m.to===data.email).text.match(/#token=([a-f0-9]+)/)[1];const newPassword='Mein komplett neuer Test Merksatz 2026!';
 assert.equal((await call('/password/finish',{token:reset,password:newPassword},{},{headers:{Origin:'https://evil.example'}})).status,403);assert.equal((await call('/password/finish',{token:reset,password:newPassword})).status,200);assert.equal((await call('/password/finish',{token:reset,password:newPassword})).status,401);assert.equal((await call('/me',undefined,customer)).status,401);assert.equal((await call('/me',undefined,second)).status,401);assert.equal((await call('/password-login',{email:data.email,password})).status,401);assert.equal((await call('/password-login',{email:data.email,password:newPassword})).status,200);
 const admin=await h.admin();assert.equal(admin.user.hasPassword,false);await call('/password/request',{email:admin.user.email});const adminToken=messages.findLast(m=>m.to===admin.user.email).text.match(/#token=([a-f0-9]+)/)[1];await call('/password/finish',{token:adminToken,password});assert.equal((await call('/password-login',{email:admin.user.email,password})).status,200);
 // Generic reset response and token invalidation on mail failure.
 const unknown=await call('/password/request',{email:'unknown@example.com'});assert.equal(unknown.status,200);h.fail(true);assert.equal((await call('/password/request',{email:data.email})).status,503);h.fail(false);assert.equal((await store.transaction(s=>s.list('password_token',customer.user.id))).length,0);
 const saltA=await P.encode(password),saltB=await P.encode(password);assert.notEqual(saltA,saltB);assert.ok(await P.verify(password,saltA));assert.equal(await P.verify('bad',saltA),false);
 }finally{await h.close();}});
test('Real referral attribution, isolated statistics, double-opt-in notifications and guarded commission payout',async t=>{const h=await harness();const {call,store,messages}=h;try{
 const admin=await h.admin(),referrer=await h.register('referrer@example.com');assert.equal((await call('/referrals/join',{accepted:false},referrer)).status,400);await call('/referrals/join',{accepted:true},referrer);const ref=(await call('/referrals',undefined,referrer)).json;assert.match(ref.code,/^UX-[A-F0-9]{12}$/);
 const client=await h.register('referred@example.com',{referralCode:ref.code}),other=await h.register('unrelated@example.com');assert.equal((await call('/referrals',undefined,referrer)).json.referredAccounts,1);assert.equal((await call('/admin/referrals',undefined,client)).status,403);
 const intake={vehicle:'Testfahrzeug',plate:'GEHEIM',accidentDate:'2026-09-09',location:'Berlin',owner:'Vertraulicher Name',ownerContact:'123',description:'Vertraulicher Schaden',authority:true,customerEmail:'additional@example.com',notifyCustomer:true};
 const made=await call('/cases',intake,client),cid=made.json.case.id;await store.transaction(async s=>{const c=await s.get('case',cid);c.status='submitted';c.submittedAt=new Date(Date.now()-86400000).toISOString();await s.put('case',c,client.user.id);});
 async function action(actor,data){const c=(await call('/cases/'+cid,undefined,admin)).json.case;return call('/cases/'+cid,{...data,version:c.version},actor);}
 // Resubmission invokes additional recipient verification without disclosing case data.
 await action(admin,{action:'status',status:'needs_info',note:'Bitte ergänzen'});await store.transaction(s=>s.put('file',{id:D.id(),caseId:cid,kind:'photo',size:1},cid));await action(client,{action:'submit'});await h.drain();const invite=messages.find(m=>m.to==='additional@example.com');assert.ok(invite);assert.doesNotMatch(invite.text,/GEHEIM|Vertraulicher/);const verify=invite.text.match(/#token=([a-f0-9]+)/)[1];
 await action(admin,{action:'status',status:'accepted'});await h.drain();assert.equal(messages.filter(m=>m.to==='additional@example.com').length,1);
 assert.equal((await call('/notifications/verify',{token:verify})).status,200);assert.equal((await call('/notifications/verify',{token:verify})).status,401);
 await action(admin,{action:'status',status:'in_progress'});await h.drain();const update=messages.findLast(m=>m.to==='additional@example.com');assert.match(update.text,/Gutachten in Arbeit/);assert.doesNotMatch(update.text,/GEHEIM|Vertraulicher/);assert.match(update.html,/cid:unfallx-logo/);
 const before=messages.length;await action(admin,{action:'internal_note',note:'Interner geheimer Text'});await h.drain();assert.equal(messages.length,before);
 const unsub=update.text.match(/#unsubscribe=([a-f0-9]+)/)[1];await call('/notifications/verify',{token:unsub});await action(admin,{action:'comment',note:'Geheimer Nachrichtentext'});await h.drain();assert.equal(messages.filter(m=>m.to==='additional@example.com').length,2);assert.ok(messages.every(m=>!m.text.includes('Geheimer Nachrichtentext')));
 // SMTP uncertainty stays visible, rather than rolling back the case or silently retrying.
 h.fail(true);await action(admin,{action:'comment',note:'Zustelltest'});await h.drain();h.fail(false);const log=(await call('/admin/notifications',undefined,admin)).json.notifications;const uncertain=log.find(n=>n.state==='uncertain');assert.ok(uncertain);assert.equal((await call('/admin/notifications/retry',{id:uncertain.id,confirmed:true},other)).status,403);assert.equal((await call('/admin/notifications/retry',{id:uncertain.id,confirmed:false},admin)).status,400);await call('/admin/notifications/retry',{id:uncertain.id,confirmed:true},admin);await h.drain();
 await store.transaction(s=>s.put('file',{id:D.id(),caseId:cid,kind:'report',size:1},cid));await action(admin,{action:'status',status:'report_ready'});await action(admin,{action:'status',status:'report_sent',confirmed:true,reference:'Versand geprüft'});await h.drain();
 const statistics=(await call('/statistics',undefined,client)).json;assert.equal(statistics.total,1);assert.equal(statistics.reports,1);assert.equal(statistics.averageDays,1);assert.equal((await call('/statistics',undefined,other)).json.total,0);assert.equal((await call('/statistics',undefined,referrer)).json.total,0);
 let reward=(await call('/referrals',undefined,referrer)).json.rewards[0];assert.ok(reward);assert.equal(reward.amount,0);assert.ok(!JSON.stringify(reward).includes(cid));assert.ok(!JSON.stringify(reward).includes(intake.owner));assert.equal((await call('/referrals',undefined,client)).json.rewards.length,0);
 const offer={id:reward.id,version:reward.version,action:'offer',amount:'100,50',settledGross:'1190',invoiceReference:'TEST-RE-1',paymentReference:'TEST-BANK-1',agreement:'Individuelle Testvereinbarung: 100,50 Euro Gesamtbetrag.',paymentConfirmed:true};assert.equal((await call('/admin/referrals',offer,other)).status,403);assert.equal((await call('/admin/referrals',{...offer,paymentConfirmed:false},admin)).status,400);assert.equal((await call('/admin/referrals',offer,admin)).status,200);assert.equal((await call('/admin/referrals',offer,admin)).status,409);
 reward=(await call('/referrals',undefined,referrer)).json.rewards[0];assert.equal((await call('/admin/referrals',{id:reward.id,version:reward.version,action:'paid',confirmed:true},admin)).status,400);assert.equal((await call('/referrals/accept',{id:reward.id,version:reward.version,accepted:true},other)).status,404);await call('/referrals/accept',{id:reward.id,version:reward.version,accepted:true},referrer);reward=(await call('/referrals',undefined,referrer)).json.rewards[0];const paid={id:reward.id,version:reward.version,action:'paid',confirmed:true,date:'2026-09-09',reference:'Banküberweisung TEST',receiptReference:'Beleg TEST'};assert.equal((await call('/admin/referrals',paid,admin)).status,200);assert.equal((await call('/admin/referrals',paid,admin)).status,409);assert.equal((await call('/referrals',undefined,referrer)).json.totals.paid,10050);
 }finally{await h.close();}});
test('OAuth JWT signature, audience, issuer, nonce, expiry and browser state fail closed',async()=>{
 const {generateKeyPair,exportJWK,SignJWT,createLocalJWKSet}=await import('jose'),{privateKey,publicKey}=await generateKeyPair('RS256'),jwk=await exportJWK(publicKey);jwk.kid='test-key';const keys=createLocalJWKSet({keys:[jwk]});
 const sign=claims=>new SignJWT({sub:'subject-1',email:'oauth@example.com',email_verified:true,nonce:'nonce-1',...claims}).setProtectedHeader({alg:'RS256',kid:'test-key'}).setIssuer(claims?.iss||'https://accounts.google.com').setAudience(claims?.aud||'test-client').setIssuedAt().setExpirationTime(claims?.exp||'5m').sign(privateKey);
 const jwt=await sign();assert.equal((await verifyIdentity(jwt,'google','test-client','nonce-1',keys)).sub,'subject-1');await assert.rejects(verifyIdentity(jwt,'google','other-client','nonce-1',keys));await assert.rejects(verifyIdentity(jwt,'google','test-client','wrong-nonce',keys));await assert.rejects(verifyIdentity(await sign({iss:'https://evil.example'}),'google','test-client','nonce-1',keys));await assert.rejects(verifyIdentity(await sign({exp:Math.floor(Date.now()/1000)-120}),'google','test-client','nonce-1',keys));const parts=jwt.split('.');parts[1]=Buffer.from(JSON.stringify({sub:'admin'})).toString('base64url');await assert.rejects(verifyIdentity(parts.join('.'),'google','test-client','nonce-1',keys));
 const h=await harness({GOOGLE_CLIENT_ID:'test-client',GOOGLE_CLIENT_SECRET:'not-a-real-secret'});try{assert.equal((await h.call('/oauth/start',{provider:'apple'})).status,503);const start=await h.call('/oauth/start',{provider:'google'});assert.equal(start.status,200);const url=new URL(start.json.redirect);assert.equal(url.origin,'https://accounts.google.com');assert.equal(url.searchParams.get('code_challenge_method'),'S256');const state=url.searchParams.get('state');assert.ok(state&&url.searchParams.get('nonce'));const cookie=start.cookie.split(';')[0];
 // Wrong browser is rejected before exchanging a code.
 assert.equal((await h.call('/oauth/google/callback?state='+state+'&code=unused')).location,'/login?oauth=failed');assert.equal((await h.call('/oauth/google/callback?state='+state+'&error=access_denied',undefined,{cookie})).location,'/login?oauth=failed');assert.equal((await h.store.transaction(s=>s.get('oauth_state',D.hash(state)))),null);
 assert.equal((await h.call('/oauth/complete',{typeOfAccount:'admin'})).status,400);assert.equal((await h.call('/oauth/start',{provider:'google',link:true})).status,401);
 }finally{await h.close();}
});

test('OAuth authorization-code success, onboarding and explicit linking never merge existing emails',async()=>{
 const {generateKeyPair,exportJWK,SignJWT}=await import('jose'),pair=await generateKeyPair('RS256'),key=await exportJWK(pair.publicKey);key.kid='oauth-flow-test';key.alg='RS256';key.use='sig';
 const h=await harness({GOOGLE_CLIENT_ID:'flow-client',GOOGLE_CLIENT_SECRET:'test-client-secret'}),originalFetch=global.fetch;let nextJWT='',lastExchange=null;
 global.fetch=async(input,options)=>{const url=String(input);if(url==='https://www.googleapis.com/oauth2/v3/certs')return new Response(JSON.stringify({keys:[key]}),{status:200,headers:{'Content-Type':'application/json'}});if(url==='https://oauth2.googleapis.com/token'){lastExchange=Object.fromEntries(options.body);return new Response(JSON.stringify({id_token:nextJWT}),{status:200,headers:{'Content-Type':'application/json'}});}return originalFetch(input,options);};
 async function flow(subject,address,actor,link=false){const start=await h.call('/oauth/start',{provider:'google',link},actor||{});assert.equal(start.status,200);const url=new URL(start.json.redirect),state=url.searchParams.get('state');nextJWT=await new SignJWT({sub:subject,email:address,email_verified:true,nonce:url.searchParams.get('nonce')}).setProtectedHeader({alg:'RS256',kid:key.kid}).setIssuer('https://accounts.google.com').setAudience('flow-client').setIssuedAt().setExpirationTime('5m').sign(pair.privateKey);const result=await h.call('/oauth/google/callback?state='+state+'&code=test-code',undefined,{cookie:start.cookie.split(';')[0]});assert.equal(result.status,303);assert.equal(lastExchange.redirect_uri,'http://localhost/api/portal/oauth/google/callback');assert.equal(Buffer.from(D.hash(lastExchange.code_verifier),'hex').toString('base64url'),url.searchParams.get('code_challenge'));return result;}
 try{
 const existing=await h.register('existing-oauth@example.com');const denied=await flow('subject-existing',existing.user.email);assert.equal(denied.location,'/login?oauth=link_required');assert.equal((await h.store.transaction(s=>s.list('identity'))).length,0);
 const linked=await flow('subject-existing',existing.user.email,existing,true);assert.equal(linked.location,'/kundenportal#einstellungen');assert.deepEqual((await h.call('/identities',undefined,existing)).json.linked,['google']);
 const signedIn=await flow('subject-existing','changed-at-provider@example.com');assert.equal(signedIn.location,'/kundenportal');assert.match(signedIn.cookie,/ux_session=/);
 await h.store.transaction(s=>s.put('security',{id:existing.user.id,mfaEnabled:true,epoch:1,phone:'+4917612345678',verifiedAt:new Date().toISOString(),recovery:[]},existing.user.id));const guarded=await flow('subject-existing',existing.user.email);assert.equal(guarded.location,'/login?factor=1');const guardedCookie=guarded.cookie.match(/ux_session=[a-f0-9]{64}/)[0];assert.equal((await h.call('/me',undefined,{cookie:guardedCookie})).status,401);

 const registration=await flow('subject-new','new-oauth@example.com');assert.equal(registration.location,'/konto-vervollstaendigen');const cookie=registration.cookie.match(/ux_onboarding=[a-f0-9]{64}/)[0],profile=(await h.call('/oauth/profile',undefined,{cookie})).json;assert.equal(profile.email,'new-oauth@example.com');
 const body={typeOfAccount:'customer',name:'OAuth Beispiel',phone:'030000',privacy:true,terms:true};assert.equal((await h.call('/oauth/complete',body,{cookie})).status,403);const complete=await h.call('/oauth/complete',body,{cookie,csrf:profile.csrf});assert.equal(complete.status,200);assert.equal(complete.json.redirect,'/kundenportal');assert.equal((await h.call('/oauth/complete',body,{cookie,csrf:profile.csrf})).status,401);const user=await h.store.transaction(s=>s.get('user',D.hash('new-oauth@example.com')));assert.equal(user.role,'customer');assert.ok(user.verifiedAt);assert.equal(user.passwordHash,undefined);assert.equal((await h.store.transaction(s=>s.list('identity'))).length,2);
 }finally{global.fetch=originalFetch;await h.close();}
});
