'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const {createAutoixpert,signedURL,payload}=require('../portal/autoixpert'),{createStore}=require('../portal/store'),D=require('../portal/domain');
const CID='sample',internal={role:'admin',id:'internal'},partner={role:'partner',id:'partner'},bytes=Buffer.from('%PDF-1.4\nUNFALLX TEST');
async function fixture(t,fetcher){const env={NODE_ENV:'test',PORTAL_LOCAL_DB:':memory:',AUTOIXPERT_API_KEY:'test-only',AUTOIXPERT_ASSESSOR_ID:'assessor'},store=await createStore(env);t.after(()=>store.close());const tx=fn=>store.transaction(fn),caseAccess=async(s,u,id)=>{const c=await s.get('case',id);D.assert(c,'not found',404);return c;},audit=async(s,u,c,a)=>{await s.put('case',c);await s.put('event',{id:D.id(),action:a},c.id);};await tx(async s=>{await s.put('case',{id:CID,number:'TEST',status:'submitted',version:2,intake:{ownerFirstName:'Test',ownerLastName:'Person',plate:'B TEST',ownership:'owned',vatDeductible:'no'},internalNote:'SECRET'});await s.blob('file',bytes);await s.put('file',{id:'file',caseId:CID,name:'Test.pdf',type:'application/pdf',kind:'document',size:bytes.length,sha256:D.hash(bytes)},CID);await s.put('file',{id:'invoice',caseId:CID,kind:'partner_invoice'},CID);});const opts={env,tx,caseAccess,audit,fetcher};return {adapter:createAutoixpert(opts),other:createAutoixpert(opts),tx};}
const json=(x,status=200)=>new Response(JSON.stringify(x),{status});
function transport(log){return async(url,o)=>{log.push({url,o});if(url.endsWith('/reports'))return json({document:{id:'report'}});if(url.endsWith('/documents'))return json({document:{id:'doc'}});if(url.endsWith('/upload'))return json({upload_url:'https://s3.eu-central-1.amazonaws.com/user-uploaded-documents-autoixpert/file?signature=test'});if(o.method==='PUT')return new Response('',{status:200});throw Error('Unexpected request');};}
test('autoiXpert only exports on explicit internal confirmation, preserves bytes and avoids charged report reads',async t=>{const log=[],{adapter,tx}=await fixture(t,transport(log));await assert.rejects(adapter.step(partner,CID,{confirmed:true,version:2}),/Nur intern/);await assert.rejects(adapter.state(partner,CID),/Nur intern/);await assert.rejects(adapter.step(internal,CID,{version:2}),/bestätigen/);assert.equal(log.length,0);await assert.rejects(adapter.step(internal,CID,{confirmed:true,version:1}),/geändert/);let r=await adapter.step(internal,CID,{confirmed:true,version:2});assert.equal(r.job.reportId,'report');r=await adapter.step(internal,CID,{});assert.equal(r.job.state,'complete');assert.equal(r.job.total,1);assert.equal(log.length,4);assert(!log.some(x=>x.o.method==='GET'&&!x.url.endsWith('/upload')));const put=log.find(x=>x.o.method==='PUT');assert.deepEqual(put.o.body,bytes);assert.equal(put.o.headers.Authorization,undefined);assert.equal(put.o.redirect,'error');assert(!log[0].o.body.includes('SECRET'));await adapter.step(internal,CID,{});assert.equal(log.length,4);assert.equal((await tx(s=>s.list('event',CID))).length,1);});
test('lost metadata responses stop automatic retries; definite rejection may safely retry',async t=>{let mode='reject',calls=0;const {adapter}=await fixture(t,async()=>{calls++;if(mode==='reject')return json({error_code:'invalid'},400);throw Error('lost connection');});await assert.rejects(adapter.step(internal,CID,{confirmed:true,version:2}),/HTTP 400/);assert.equal((await adapter.state(internal,CID)).job.state,'error');mode='lost';await assert.rejects(adapter.step(internal,CID,{}),/nicht bestätigt/);assert.equal((await adapter.state(internal,CID)).job.state,'uncertain');await assert.rejects(adapter.step(internal,CID,{}),/kein zweiter/);assert.equal(calls,2);});
test('failed original upload resumes same remote document without duplicate metadata',async t=>{let fail=true;const log=[],base=transport(log),{adapter}=await fixture(t,async(url,o)=>{if(o.method==='PUT'&&fail){log.push({url,o});throw Error('offline');}return base(url,o);});await adapter.step(internal,CID,{confirmed:true,version:2});await assert.rejects(adapter.step(internal,CID,{}),/unterbrochen/);fail=false;assert.equal((await adapter.step(internal,CID,{})).job.state,'complete');assert.equal(log.filter(x=>x.url.endsWith('/documents')).length,1);});
test('durable transfer claim excludes a second server instance',async t=>{let release,started;const waiting=new Promise(r=>started=r),gate=new Promise(r=>release=r);const {adapter,other}=await fixture(t,async()=>{started();await gate;return json({document:{id:'one'}});});const first=adapter.step(internal,CID,{confirmed:true,version:2});await waiting;await assert.rejects(other.step(internal,CID,{confirmed:true,version:2}),/anderen Sitzung/);release();assert.equal((await first).job.reportId,'one');});
test('signed uploads are restricted to documented Frankfurt buckets and ownership maps correctly',()=>{assert.equal(payload({id:'a',intake:{ownership:'owned',vatDeductible:'yes'}},'b').claimant.is_owner,true);for(const value of ['http://s3.eu-central-1.amazonaws.com/photos-autoixpert/a','https://example.org/a','https://photos-autoixpert.s3.eu-central-1.amazonaws.com.evil.example/a','https://s3.eu-central-1.amazonaws.com/wrong/a','https://user:pass@s3.eu-central-1.amazonaws.com/photos-autoixpert/a'])assert.throws(()=>signedURL(value));assert(signedURL('https://photos-autoixpert.s3.eu-central-1.amazonaws.com/a'));});
test('native app claimant fields reach autoiXpert structured fields without inventing consent',()=>{
 const p=payload({id:'native',intake:{plate:'B TEST'},mobile:{fields:{'claimant.first':'Alex','claimant.last':'Test','claimant.email':'alex@example.test','claimant.street':'Teststraße 2','claimant.iban':'TEST-IBAN'}}},'assessor');assert.equal(p.claimant.first_name,'Alex');assert.equal(p.claimant.email,'alex@example.test');assert.equal(p.claimant.iban,'TEST-IBAN');assert(!p.claimant.notes.includes('berechtigt. Die betroffenen Personen'));
});
