'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),sharp=require('sharp');
const I=require('../assets/case-intake'),{Batch}=require('../assets/uploads'),D=require('../portal/domain'),fixture=require('./fixtures/intake'),{createStore}=require('../portal/store'),{createPortal}=require('../portal/app');
test('Complete intake covers ownership, optional opponent data and conditional inspection details',()=>{
 const base=fixture();assert.deepEqual(I.errors(base),[]);
 for(const ownership of Object.keys(I.options.ownership))assert.deepEqual(I.errors({...base,ownership}),[]);
 const company={...base,ownerType:'company',ownerCompany:'Beispiel GmbH',ownerPostbox:'1234',vatDeductible:'yes',inspectionConditionsAdequate:'no',inspectionConditionsNote:'Unterboden nicht zugänglich',inspectionToolsUsed:'yes',inspectionTools:['measuring_rod','lift','other'],inspectionToolsOther:'Prüflampe',inspectionAlone:false,inspectionAttendees:'Erika Beispiel – Auftraggeberin',previousDamage:'repaired',previousDamageDescription:'Kotflügel instand gesetzt',lawyerChoice:'own',lawyerName:'Beispielkanzlei',opponentCompany:'Gegner GmbH',opponentFirstName:'Max',opponentLastName:'Beispiel',opponentStreet:'Gegnerstraße',opponentHouseNumber:'6',opponentPostcode:'04109',opponentCity:'Leipzig',opponentPhone:'+493411234567',opponentEmail:'opponent@example.com',insurer:'Beispielversicherung',insuranceNumber:'TEST-POLICE',claimNumber:'TEST-SCHADEN'};
 assert.deepEqual(I.errors(company),[]);assert.equal(D.intake({...company,ownerType:'person'}).owner,'Erika Beispiel');const unassigned=D.intake({...company,lawyerChoice:'undecided',shareWithLawyer:true,lawyerEmail:'old@example.com'});assert.equal(unassigned.lawyerEmail,'');assert.equal(unassigned.shareWithLawyer,false);assert.equal(D.intake(company).owner,'Beispiel GmbH · Erika Beispiel');assert.deepEqual(D.intake(company).inspectionTools,['measuring_rod','lift','other']);
 for(const key of ['ownerCompany','inspectionConditionsNote','inspectionTools','inspectionToolsOther','inspectionAttendees','previousDamageDescription','lawyerName'])assert.ok(I.errors({...company,[key]:key==='inspectionTools'?[]:''}).some(e=>e.name===key),key);
 for(const key of ['opponentCompany','opponentFirstName','opponentLastName','opponentStreet','opponentHouseNumber','opponentPostcode','opponentCity','opponentPhone','opponentEmail','insurer','insuranceNumber','claimNumber','ownerPostbox'])assert.deepEqual(I.errors({...company,[key]:''}),[],key);
});
test('Unknown opponent plate requires known police number; no silent empty-plate bypass',()=>{
 const base=fixture();assert.ok(I.errors({...base,opponentPlate:''}).some(e=>e.name==='opponentPlate'));
 const unknown={...base,opponentPlateUnknown:true,opponentPlate:'stale plate',policeInvolved:'no'};const errors=I.errors(unknown);assert.ok(errors.some(e=>e.name==='policeFileNumber'));assert.ok(errors.some(e=>e.name==='policeAuthority'));assert.ok(!errors.some(e=>e.name==='opponentPlate'));
 const valid={...unknown,policeFileNumber:'BE-2026-TEST-123',policeAuthority:'Beispieldienststelle Berlin'};assert.deepEqual(I.errors(valid),[]);assert.equal(D.intake(valid).policeInvolved,'yes');assert.equal(D.intake(valid).opponentPlate,'');
 assert.ok(I.errors({...valid,opponentPlateUnknown:false,opponentPlate:''}).some(e=>e.name==='opponentPlate'));
});
test('IBAN, FIN, time, HU and mileage are validated on submission while drafts preserve unfinished input',()=>{
 const base=fixture();assert.equal(D.intake({...base,ownerIban:'de89 3704 0044 0532 0130 00'}).ownerIban,'DE89370400440532013000');
 for(const [name,value]of [['ownerIban','DE00370400440532013000'],['customerEmail','bad'],['opponentEmail','bad'],['vin','WBAII12345'],['mileage','12.000'],['huDue','2027-13'],['accidentDate','2026-02-30'],['accidentTime','25:10'],['inspectionDate','bad'],['inspectionTime','99:00']])assert.ok(I.errors({...base,[name]:value}).some(e=>e.name===name),name);
 const draft=D.intake({vehicle:'Nur ein Entwurf',ownerIban:'DE89',mileage:'12.'});assert.equal(draft.ownerIban,'DE89');assert.equal(draft.mileage,'12.');assert.ok(I.errors(draft).length>20);
 assert.throws(()=>D.intake({...base,inspectionTools:['__proto__']}),/Hilfsmittel/);assert.throws(()=>D.intake({...base,ownership:'constructor'}),/Auswahl/);assert.throws(()=>D.intake({...base,ownerIban:1234}),/Textfeld/);assert.throws(()=>D.intake({...base,inspectionAttendees:'x'.repeat(2001)}),/Pflichtfelder/);
 assert.deepEqual(I.fileErrors([{kind:'photo'},{kind:'registration'},{kind:'authorization'}]),[]);assert.deepEqual(I.fileErrors([{kind:'photo'},{kind:'case_bundle'}]),[]);assert.equal(I.fileErrors([{kind:'document'},{kind:'photo'}]).length,2);
});
test('Upload selection can classify originals without re-encoding them or misclassifying a PDF as photo',async()=>{
 const pdf=new File(['%PDF-1.4\n%%EOF'],'Auftrag.pdf',{type:'application/pdf'}),photo=new File(['bytes unchanged'],'Fahrzeugschein.jpg',{type:'image/jpeg'}),q=new Batch();q.add([pdf,photo]);q.classify(q.items[0],'authorization');q.classify(q.items[1],'registration');assert.throws(()=>q.classify(q.items[0],'photo'),/Dateiart/);
 await q.send(async item=>{assert.equal(item.file,item.kind==='authorization'?pdf:photo);return item.kind;});assert.deepEqual(q.items.map(i=>i.result),['authorization','registration']);assert.throws(()=>q.classify(q.items[0],'document'),/Fallakte/);
});
test('Structured intake survives save, reload, file classification and submit, with tenant and status protection',async t=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'ux-intake-')),env={NODE_ENV:'test',PORTAL_LOCAL_DB:path.join(dir,'db.sqlite'),PORTAL_ORIGIN:'http://localhost'},store=await createStore(env),sent=[];const portal=createPortal({env,store,mail:{ready:true,send:async(...v)=>sent.push(v)}});await portal.ready();const server=http.createServer((req,res)=>portal.handle(req,res,{}));await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;
 async function actor(role,name){const id=D.hash(name),token=D.random(),csrf=D.random(),companyId=role==='partner'?id:null;await store.transaction(async s=>{await s.put('user',{id,name,email:name+'@example.com',role,companyId,active:true,verifiedAt:new Date().toISOString()},companyId||'internal');if(companyId)await s.put('company',{id:companyId,name,status:'approved'});await s.put('session',{id:D.hash(token),userId:id,csrf,createdAt:new Date().toISOString(),expires:Date.now()+3600000},id);});return {id,Cookie:'ux_session='+token,'X-CSRF-Token':csrf};}
 async function call(p,data,u={},headers={}){const r=await fetch(base+'/api/portal'+p,{method:data===undefined?'GET':'POST',headers:{Origin:env.PORTAL_ORIGIN,'Content-Type':'application/json',...u,...headers},body:data===undefined?undefined:Buffer.isBuffer(data)?data:JSON.stringify(data)});const bytes=Buffer.from(await r.arrayBuffer());return {status:r.status,headers:r.headers,bytes,json:r.headers.get('content-type')?.includes('application/json')?JSON.parse(bytes):null};}
 try{
 const partner=await actor('partner','fixture-partner'),other=await actor('partner','fixture-other'),admin=await actor('admin','fixture-admin'),staff=await actor('appraiser','fixture-staff');
 const made=await call('/cases',{vehicle:'Entwurf',ownerIban:'DE89'},partner);assert.equal(made.status,200);const cid=made.json.case.id;assert.equal(made.json.case.status,'draft');assert.equal(made.json.case.intake.ownerIban,'DE89');
 async function act(data,u=partner){const version=(await call('/cases/'+cid,undefined,admin)).json.case.version;return call('/cases/'+cid,{...data,version},u);}
 await t.test('Incomplete drafts return actionable fields; forged roles and complete flags cannot bypass submission',async()=>{
  const missing=await act({action:'submit',complete:true,role:'admin'});assert.equal(missing.status,400);assert.ok(missing.json.fields.some(f=>f.name==='ownerFirstName'));assert.ok(missing.json.fields.some(f=>f.name==='registration'));assert.equal((await call('/cases/'+cid,undefined,admin)).json.case.status,'draft');
  assert.equal((await act({action:'partner_status',status:'recording'})).status,200);assert.equal((await act({action:'partner_status',status:'ready_to_submit'})).status,400);
  assert.equal((await act({action:'status',status:'submitted'},admin)).status,400);assert.equal((await call('/cases/'+cid,undefined,other)).status,404);assert.equal((await call('/cases/'+cid,undefined,staff)).status,404);
 });
 const complete={...fixture(),ownerPostbox:'777',ownership:'manufacturer_bank',financeCompany:'Beispiel-Herstellerbank',previousDamage:'unrepaired',previousDamageDescription:'Alter Kratzer an der hinteren Tür',opponentPlateUnknown:true,policeFileNumber:'TEST-AZ-456',policeAuthority:'Testwache',inspectionConditionsAdequate:'no',inspectionConditionsNote:'Unterboden eingeschränkt sichtbar',inspectionToolsUsed:'yes',inspectionTools:['lift','measuring_rod'],inspectionAlone:false,inspectionAttendees:'Erika Beispiel – Auftraggeberin',lawyerChoice:'unfallx',shareWithLawyer:true};
 const saved=await act({action:'save',...complete,lawyerEmail:'injected@example.com',lawyerName:'Nicht zugeordnet'});assert.equal(saved.status,200);assert.deepEqual(saved.json.case.intake,D.intake(complete));const reloaded=await call('/cases/'+cid,undefined,admin);assert.deepEqual(reloaded.json.case.intake,D.intake(complete));assert.match(reloaded.headers.get('cache-control'),/no-store/);
 const pdf=Buffer.from('%PDF-1.4\nFixture Auftrag und Fahrzeugschein\n%%EOF'),pic=await sharp({create:{width:4,height:4,channels:3,background:'#999'}}).jpeg().toBuffer();
 async function upload(kind,bytes,type,name,u=partner){return call('/cases/'+cid+'/files',bytes,u,{'Content-Type':type,'X-File-Kind':kind,'X-File-Name':name});}
 assert.equal((await upload('photo',pdf,'application/pdf','wrong.pdf')).status,400);assert.equal((await upload('photo',pic,'image/jpeg','Schaden.jpg')).status,200);const file=(await upload('document',pdf,'application/pdf','Auftrag-und-Schein.pdf')).json.file;
 await t.test('Existing files can be assigned without losing original bytes; unrelated or released files cannot be repurposed',async()=>{
  assert.equal((await act({action:'file_kind',fileId:file.id,kind:'case_bundle'},other)).status,404);assert.equal((await act({action:'file_kind',fileId:file.id,kind:'report'})).status,400);assert.equal((await act({action:'file_kind',fileId:file.id,kind:'photo'})).status,400);assert.equal((await act({action:'file_kind',fileId:D.id(),kind:'case_bundle'})).status,404);
  assert.equal((await act({action:'submit'})).status,400);assert.equal((await act({action:'file_kind',fileId:file.id,kind:'case_bundle'})).status,200);assert.deepEqual((await call('/files/'+file.id,undefined,admin)).bytes,pdf);
  assert.equal((await act({action:'partner_status',status:'ready_to_submit'})).status,200);const submitted=await act({action:'submit'});assert.equal(submitted.status,200,JSON.stringify(submitted.json));assert.equal(submitted.json.case.status,'submitted');assert.deepEqual(submitted.json.case.intake,D.intake(complete));assert.equal((await act({action:'file_kind',fileId:file.id,kind:'document'})).status,403);assert.equal((await act({action:'save',...complete,ownerIban:'DE89'})).status,403);
 });
 await t.test('New sensitive fields stay within authorized views and are not included in status notifications',async()=>{
  const exp=(await call('/export',undefined,partner)).json;assert.deepEqual(exp.cases[0].intake,D.intake(complete));assert.equal((await call('/export',undefined,other)).json.cases.length,0);
  const token=D.random();await store.transaction(s=>s.put('tracking_token',{id:D.hash(token),caseId:cid,email:complete.customerEmail,epoch:reloaded.json.case.trackingEpoch||0,expires:Date.now()+3600000},cid));const status=await call('/tracking',{token});assert.equal(status.status,200);const exposed=JSON.stringify(status.json);for(const value of [complete.ownerIban,complete.vin,complete.ownerStreet,complete.policeFileNumber,complete.inspectionAttendees])assert.ok(!exposed.includes(value));
  for(let n=0;n<100;n++){const rows=await store.transaction(s=>s.list('notification'));if(!rows.some(r=>['pending','sending'].includes(r.state)))break;await new Promise(r=>setTimeout(r,10));}assert.ok(sent.length>0);const mails=JSON.stringify(sent);for(const value of [complete.ownerIban,complete.vin,complete.ownerStreet,complete.inspectionAttendees])assert.ok(!mails.includes(value),value);
  const direct=await call('/cases',{...fixture(),draft:false,status:'submitted'},admin);assert.equal(direct.json.case.status,'draft');assert.equal((await call('/cases',{},admin)).status,400);
 });
 }finally{await new Promise(r=>server.close(r));await portal.close();fs.rmSync(dir,{recursive:true,force:true});}
});
