'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),sharp=require('sharp');
const {createMobileIntake,clean,asIntake}=require('../portal/mobile-intake');
const {createStore}=require('../portal/store');
const valid={'claimant.first':'Alex','claimant.last':'Beispiel','claimant.street':'Musterstraße 12','claimant.zip':'10115','claimant.city':'Berlin',plate:'B UX 123'};
async function setup(){const s=await createStore({NODE_ENV:'test',PORTAL_LOCAL_DB:':memory:'});const tx=fn=>s.transaction(fn);const rate=async()=>{};const body=async(req,max,raw)=>{if(raw)return req.bytes;return req.payload};const api=createMobileIntake({tx,body,rate,ip:()=> 'test',env:{PORTAL_MOBILE_INTAKE_ENABLED:'true'},authorize:async()=>({user:{id:'p',name:'Testpartner',role:'partner',companyId:'co'},company:{id:'co',status:'approved',name:'Testfirma'}})});return {s,tx,api};}
function req(key,payload,headers={},bytes){return {method:'POST',headers:{authorization:'Bearer '+key,...headers},payload,bytes};}
const key=()=>crypto.randomBytes(32).toString('hex'),id=()=>crypto.randomUUID();
const make=(cid,f=valid)=>({id:cid,fields:f,fieldsHash:crypto.createHash('sha256').update(JSON.stringify(f)).digest('hex'),reference:'TEST'});
test('all mandatory fields, whitespace and unexpected fields rejected',()=>{for(const k of Object.keys(valid)){assert.throws(()=>clean({...valid,[k]:'  '}));}assert.throws(()=>clean({...valid,isAdmin:'true'}));assert.equal(asIntake(valid).owner,'Alex Beispiel');});
test('case is visible in existing admin store; capability is separate; retries do not duplicate',async()=>{const {s,tx,api}=await setup();try{const cid=id(),k=key();await api.route('/mobile/cases',req(k,make(cid)));await api.route('/mobile/cases',req(k,make(cid)));const cases=await tx(q=>q.list('case'));assert.equal(cases.length,1);assert.equal(cases[0].source,'mobile');assert.equal(cases[0].intake.owner,'Alex Beispiel');assert(!JSON.stringify(cases).includes(k));await assert.rejects(api.route('/mobile/cases',req(key(),make(cid))),e=>e.status===404);}finally{await s.close();}});
test('same file retries are idempotent; cross-case writes and modified reuse are blocked',async()=>{const {s,tx,api}=await setup();try{const cid=id(),k=key();await api.route('/mobile/cases',req(k,make(cid)));const bytes=await sharp({create:{width:10,height:10,channels:3,background:'red'}}).jpeg().toBuffer();const headers={'x-file-kind':'photo','x-file-name':'Front.jpg','x-asset-id':id(),'x-perspective':'frontLeft','content-type':'image/jpeg'};const path='/mobile/cases/'+cid+'/files';await api.route(path,req(k,null,headers,bytes));const retry=await api.route(path,req(k,null,headers,bytes));assert.equal(retry.alreadyStored,true);assert.equal((await tx(q=>q.list('file',cid))).length,1);await assert.rejects(api.route(path,req(key(),null,headers,bytes)),e=>e.status===404);const changed=await sharp({create:{width:10,height:10,channels:3,background:'blue'}}).jpeg().toBuffer();await assert.rejects(api.route(path,req(k,null,headers,changed)),e=>e.status===409);}finally{await s.close();}});
test('corrupt photos and internal report upload are rejected without files',async()=>{const {s,tx,api}=await setup();try{const cid=id(),k=key();await api.route('/mobile/cases',req(k,make(cid)));const path='/mobile/cases/'+cid+'/files';for(const kind of ['photo','report']){await assert.rejects(api.route(path,req(k,null,{'x-file-kind':kind,'x-file-name':'x.jpg','x-asset-id':id(),'content-type':'image/jpeg'},Buffer.from('bad'))));}assert.equal((await tx(q=>q.list('file',cid))).length,0);}finally{await s.close();}});
test('completion needs all perspectives and two current orders; completion retries succeed',async()=>{const {s,tx,api}=await setup();try{const cid=id(),k=key(),data=make(cid);await api.route('/mobile/cases',req(k,data));await assert.rejects(api.route('/mobile/cases/'+cid+'/finish',req(k,{})),e=>e.status===400);const bytes=await sharp({create:{width:10,height:10,channels:3,background:'white'}}).jpeg().toBuffer();for(const p of ['frontLeft','frontRight','rearRight','rearLeft','damageOverview','damageDetail','plate','vin','odometer','registration'])await api.route('/mobile/cases/'+cid+'/files',req(k,null,{'x-file-kind':p==='registration'?'registration':'photo','x-file-name':p+'.jpg','x-asset-id':id(),'x-perspective':p,'content-type':'image/jpeg'},bytes));for(const kind of ['unfallx','nextright'])await api.route('/mobile/cases/'+cid+'/files',req(k,null,{'x-file-kind':'authorization','x-file-name':kind+'.pdf','x-asset-id':id(),'content-type':'application/pdf','x-order-kind':kind,'x-fields-hash':data.fieldsHash},Buffer.from('%PDF-1.7\nTest-only fixture\n%%EOF')));await api.route('/mobile/cases/'+cid+'/finish',req(k,{}));await api.route('/mobile/cases/'+cid+'/finish',req(k,{}));await api.route('/mobile/cases',req(k,data));assert.equal((await tx(q=>q.get('case',cid))).status,'submitted');await assert.rejects(api.route('/mobile/cases',req(k,make(cid,{...valid,plate:'ANDERS'}))),e=>e.status===409);}finally{await s.close();}});
test('endpoint can be explicitly disabled',async()=>{const {s,tx}=await setup();try{const api=createMobileIntake({tx,body:async()=>{},rate:async()=>{},ip:()=> 'test',env:{PORTAL_MOBILE_INTAKE_ENABLED:'false'}});await assert.rejects(api.route('/mobile/cases',req(key(),{})),e=>e.status===501);}finally{await s.close();}});

test('zero commission is explicit and never payable',()=>{const c=require('../portal/mobile-intake').commission({finance:{partnerNet:0,invoiceNet:10000,invoiceGross:11900,received:11900}});assert.equal(c.amountCents,0);assert.equal(c.stage,'no_commission');assert.equal(c.payable,false);});
