'use strict';
const D=require('./domain');
const hosts=require('./hosts');
const caseFolders=require('./case-folders');
const {AsyncLocalStorage}=require('node:async_hooks');
const {isPortalRole,assertPortalUser,unavailable}=require('./access');
const {createStore}=require('./store');
const {storageConfig}=require('./file-storage');
const {createStorageAdmin}=require('./storage-admin');
const {createMailer}=require('./mail');
const sharp=require('sharp');
const {sendArchive}=require('./file-archive');
const {accessEmail}=require('./email-templates');
const passwords=require('./passwords');
const {notice}=require('./brand-mail');
const {publicUser}=D;
const {createOAuth}=require('./oauth');
const {createReferrals}=require('./referrals');
const {createNotifications}=require('./notifications');
const {createSecurity}=require('./security');
const {statistics}=require('./statistics');
const {createTracking}=require('./tracking');
const {createDocuments}=require('./documents');
const {createLawyers}=require('./lawyers');
const financeMath=require('../assets/finance-math');
const external=u=>u.role==='partner';
const internal=u=>['admin','appraiser'].includes(u.role);
const owner=c=>c.companyId||c.ownerUserId;
const visible=(u,c)=>u.role==='admin'||u.role==='partner'&&c.companyId===u.companyId||u.role==='appraiser'&&c.assignee===u.id;
const {assert,text,email,id,hash,random,Problem}=D;
const hour=3600000;
function createPortal(options={}) {
 const env=options.env||process.env;
 const local=env.NODE_ENV==='test';
 const origin=local?(env.PORTAL_ORIGIN||'https://unfallx.com'):(!env.PORTAL_ORIGIN||env.PORTAL_ORIGIN==='https://unfallx.com'?'https://app.unfallx.com':env.PORTAL_ORIGIN);
 const context=new AsyncLocalStorage();
 const scope=()=>context.getStore()||{};
 const requestOrigin=()=>scope().origin||origin;
 const recipientOrigin=user=>local&&!scope().production?origin:(internal(user)?hosts.ADMIN_ORIGIN:hosts.APP_ORIGIN);
 function checkWorkspace(user){const w=scope().workspace;if(w)assert(hosts.workspaces[w].roles.includes(user.role),internal(user)?'Dieser Zugang gehört zum internen Team. Bitte unter admin.unfallx.com anmelden.':'Dieser Zugang gehört zum Partner-Portal. Bitte unter app.unfallx.com anmelden.',403);}
 const cookieName=local?'ux_session':'__Host-ux_session';
 const adminEmail=email(env.PORTAL_ADMIN_EMAIL||'info@unfallx.com');
 const mail=options.mail||createMailer(env);
 let database=null,starting=null,lastFailure=0;
 async function db(){if(database)return database;if(Date.now()-lastFailure<15000)throw new Problem(503,'Das Portal wird gerade vorbereitet. Bitte in wenigen Minuten erneut versuchen.');if(!starting)starting=(options.store?Promise.resolve(options.store):createStore(env)).then(async s=>{const probe=id(),bytes=Buffer.from('UNFALLX storage probe');await s.transaction(async q=>{await q.put('probe',{id:probe,value:'ok'});await q.probeBlob(probe,bytes);});await s.transaction(async q=>{const row=await q.get('probe',probe),saved=await q.probeBlob(probe);if(row?.value!=='ok'||!saved?.equals(bytes))throw new Error('DATABASE_INTEGRITY');await q.remove('probe',probe);await q.removeBlob(probe);});return database=s;}).catch(e=>{lastFailure=Date.now();console.error('Portal database unavailable:',e.code||'configuration');throw new Problem(503,'Das Portal ist vorübergehend nicht erreichbar. Bitte später erneut versuchen.');}).finally(()=>{starting=null;});return starting;}
 const tx=async fn=>(await db()).transaction(fn);
 const storageAdmin=createStorageAdmin({tx,env,rate});
 function sessionCookie(value,maxAge=43200){return `${cookieName}=${value}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${maxAge}${local?'':'; Secure'}`;}
 async function body(req,max=40000,raw=false){assert(Number(req.headers['content-length']||0)<=max,'Datei oder Eingabe ist zu groß.',413);if(!raw)assert((req.headers['content-type']||'').split(';')[0]==='application/json','JSON erwartet.',415);const chunks=[];let bytes=0;for await(const chunk of req){bytes+=chunk.length;assert(bytes<=max,'Datei oder Eingabe ist zu groß.',413);chunks.push(chunk);}const b=Buffer.concat(chunks);if(raw)return b;try{return JSON.parse(b.toString('utf8'));}catch{throw new Problem(400,'Ungültige Eingabe.');}}
 async function rate(s,key,max,window=hour){const stamp=Math.floor(Date.now()/window);const rid=hash(key+':'+stamp);let r=await s.get('limit',rid)||{id:rid,count:0,expires:(stamp+2)*window};assert(r.count<max,'Zu viele Versuche. Bitte später erneut versuchen.',429);r.count++;await s.put('limit',r);}
 async function auth(req,s,allowPending=false){const cookie=(req.headers.cookie||'').split(';').map(v=>v.trim()).find(v=>v.startsWith(cookieName+'='));assert(cookie,'Bitte anmelden.',401);const token=cookie.slice(cookieName.length+1);assert(/^[a-f0-9]{64}$/.test(token),'Bitte erneut anmelden.',401);const session=await s.get('session',hash(token));assert(session&&session.expires>Date.now(),'Deine Sitzung ist abgelaufen. Bitte erneut anmelden.',401);const user=await s.get('user',session.userId);assert(user&&user.active,'Der Zugang ist gesperrt.',403);assertPortalUser(user);checkWorkspace(user);if(user.role==='partner'){const company=await s.get('company',user.companyId);assert(company&&company.status!=='suspended','Der Firmenzugang ist gesperrt.',403);}assert(!scope().workspace||session.workspace===scope().workspace,'Bitte in diesem Bereich neu anmelden.',401);assert(allowPending||!session.pendingMfa,'Bitte die Zwei-Faktor-Anmeldung abschließen.',401);if(req.method!=='GET')assert(req.headers['x-csrf-token']===session.csrf,'Bitte die Seite neu laden.',403);return {user,session};}
 const isAdmin=u=>assert(u.role==='admin','Nur die Administration darf diese Aktion ausführen.',403);
 const redirectFor=user=>user.role==='partner'?'/portal':'/gutachter-portal';
 async function enabled(s,user){assert(user&&user.active,'Der Zugang ist gesperrt.',403);assertPortalUser(user);checkWorkspace(user);if(user.role==='partner')assert((await s.get('company',user.companyId))?.status!=='suspended','Der Firmenzugang ist gesperrt.',403);}
 async function issueSession(s,user,proof=null){await enabled(s,user);const safety=await security.record(s,user),pending=!!safety.mfaEnabled&&!proof;const secret=random(),session={id:hash(secret),userId:user.id,workspace:scope().workspace||null,csrf:random(),createdAt:new Date().toISOString(),expires:Date.now()+(pending?10*60000:12*hour),pendingMfa:pending,securityEpoch:safety.epoch,recoveryLogin:!!proof?.recovery,mfaVerifiedAt:proof?new Date().toISOString():null};await s.put('session',session,user.id);return {cookie:sessionCookie(secret,pending?600:43200),redirect:pending?'/login?factor=1':redirectFor(user),mfaRequired:pending};} 
 async function passwordLogin(req,data){const address=email(data.email);const user=await tx(async s=>{await rate(s,'password-ip:'+ip(req),25,15*60000);await rate(s,'password-email:'+address,30);return s.get('user',hash(address));});const ok=await passwords.verify(data.password,user?.passwordHash);assert(ok&&user?.verifiedAt&&user.active,'E-Mail oder Passwort stimmt nicht. Prüfe auch deine E-Mail-Bestätigung.',401);return tx(async s=>{const fresh=await s.get('user',user.id);assert(fresh?.passwordHash===user.passwordHash,'Bitte erneut anmelden.',401);return issueSession(s,fresh);});}
 async function passwordReset(req,data){assert(mail.ready,'Der E-Mail-Versand ist vorübergehend nicht verfügbar.',503);const address=email(data.email);const delivery=await tx(async s=>{await rate(s,'reset-ip:'+ip(req),10);await rate(s,'reset-email:'+address,3);const user=await s.get('user',hash(address));if(!user?.active||!user.verifiedAt||!isPortalRole(user.role))return null;for(const old of await s.list('password_token',user.id))await s.remove('password_token',old.id);const token=random();await s.put('password_token',{id:hash(token),userId:user.id,version:user.passwordHash||'',expires:Date.now()+30*60000},user.id);return {token,user};});if(delivery){const e=notice({title:'Dein Passwort festlegen',copy:'Du hast ein neues Passwort angefordert. Der persönliche Link gilt 30 Minuten und ist einmal verwendbar. Wenn du diese Nachricht nicht angefordert hast, ignoriere sie. Dein bisheriger Zugang bleibt unverändert.',url:recipientOrigin(delivery.user)+'/passwort#token='+delivery.token,cta:'Neues Passwort festlegen',origin:recipientOrigin(delivery.user)});try{await mail.send(address,e.subject,e.text,[],e.html);}catch{await tx(s=>s.remove('password_token',hash(delivery.token)));throw new Problem(503,'Die E-Mail konnte gerade nicht versandt werden. Bitte später erneut versuchen.');}}return {message:'Wenn ein bestätigtes Konto zu dieser Adresse besteht, erhältst du einen Link zum Festlegen eines Passworts. Bitte auch den Spamordner prüfen.'};}
 async function finishPassword(req,data){assert(/^[a-f0-9]{64}$/.test(data.token||''),'Ungültiger Link.');await tx(s=>rate(s,'reset-finish:'+ip(req),12));const key=hash(data.token),record=await tx(s=>s.get('password_token',key));assert(record&&record.expires>Date.now(),'Der Link ist abgelaufen oder wurde bereits verwendet.',401);const encoded=await passwords.encode(data.password);const address=await tx(async s=>{const token=await s.get('password_token',key),user=token&&await s.get('user',token.userId);assert(token&&token.expires>Date.now()&&user?.active&&(user.passwordHash||'')===token.version,'Der Link ist abgelaufen oder wurde bereits verwendet.',401);assertPortalUser(user);checkWorkspace(user);user.passwordHash=encoded;user.passwordChangedAt=new Date().toISOString();await s.put('user',user,user.companyId||'internal');for(const kind of ['session','password_token','sms_challenge'])for(const r of await s.list(kind,user.id))await s.remove(kind,r.id);for(const r of await s.list('token',user.email))await s.remove('token',r.id);return user;});const e=notice({title:'Dein Passwort wurde geändert',copy:'Dein neues Passwort ist gespeichert. Alle bisherigen Sitzungen wurden abgemeldet. Falls du diese Änderung nicht vorgenommen hast, fordere sofort ein neues Passwort an und kontaktiere info@unfallx.com.',url:recipientOrigin(address)+'/login',cta:'Mit Passwort anmelden',origin:recipientOrigin(address)});try{await mail.send(address.email,e.subject,e.text,[],e.html);}catch{console.error('Password change notice: delivery unavailable');}return {message:'Passwort gespeichert. Melde dich jetzt mit deiner E-Mail und deinem neuen Passwort an.'};}
 async function caseAccess(s,user,cid){const c=await s.get('case',cid);assert(c&&(visible(user,c)),'Fall nicht gefunden.',404);return c;}
 async function audit(s,user,c,action,note='',internal=false){const event={id:id(),caseId:c.id,actor:user.name,action,note,internal,at:new Date().toISOString()};await s.put('event',event,c.id);c.updatedAt=new Date().toISOString();c.version++;await s.put('case',c,owner(c));await notifications.event(s,user,c,event);await referrals.sync(s,c);}
 async function cleanup(s){for(const r of await s.list('notification'))if(['sent','cancelled'].includes(r.state)&&Date.parse(r.createdAt)<Date.now()-90*24*hour)await s.remove('notification',r.id);for(const kind of ['sms_challenge','sms_guard','security_event','tracking_token','lawyer_token','token','password_token','oauth_state','oauth_pending','notification_token','academy_token','session','limit'])for(const r of await s.list(kind))if(r.expires<Date.now())await s.remove(kind,r.id);}
 async function loginRequest(req,data,register){assert(!register||scope().workspace!=='admin','Interne Zugänge werden ausschließlich durch die Administration eingeladen.',403);assert(mail.ready,'Der E-Mail-Login ist vorübergehend nicht verfügbar.',503);const address=email(data.email);const company=register===true?D.companyData(data):null;if(register){assert(data.privacy===true,'Bitte die Datenschutzhinweise bestätigen.');assert(data.terms===true,'Bitte die Nutzungsbedingungen bestätigen.');passwords.password(data.password);}await tx(s=>rate(s,'auth-hash:'+ip(req),20));const encoded=register?await passwords.encode(data.password):null;let delivery;
 await tx(async s=>{await rate(s,'auth-ip:'+ip(req),15);await rate(s,'auth-email:'+address,4);await rate(s,'auth-global',120);await cleanup(s);const user=await s.get('user',hash(address));if(!register&&!user&&address!==adminEmail)return;if(user&&(!user.active||!isPortalRole(user.role)))return;if(register)for(const old of await s.list('token',address))if(old.passwordHash)await s.remove('token',old.id);const token=random();const record={id:hash(token),email:address,passwordHash:!user?encoded:null,termsVersion:register?'2026-09-09':null,referralCode:!user?text(data.referralCode,32).toUpperCase():'',company:!user&&address!==adminEmail?company:null,expires:Date.now()+15*60000};await s.put('token',record,address);delivery={to:address,token,user:user||{role:address===adminEmail?'admin':'partner'}};});
 if(delivery)try{const content=accessEmail({kind:register?'registration':'login',name:company?.contact||'',company:company?.name||'',url:recipientOrigin(delivery.user||delivery.member)+'/login#token='+delivery.token,origin:recipientOrigin(delivery.user||delivery.member)});await mail.send(delivery.to,content.subject,content.text,[],content.html);}catch{await tx(s=>s.remove('token',hash(delivery.token)));throw new Problem(503,'Der Login-Link konnte gerade nicht versandt werden. Bitte später erneut versuchen.');}
 return {message:'Wenn die Adresse für diesen Zugang verfügbar ist, erhältst du einen Login-Link. Bitte auch den Spamordner prüfen.'};}
 function ip(req){ // Hostinger terminates TLS; trust only its nearest forwarded hop when explicitly configured.
 const forwarded=env.PORTAL_TRUST_PROXY==='true'?String(req.headers['x-forwarded-for']||'').split(',').pop().trim():'';
 return forwarded||req.socket.remoteAddress||'unknown';}
 async function exchange(req,data){assert(/^[a-f0-9]{64}$/.test(data.token||''),'Der Login-Link ist ungültig.',400);await tx(s=>rate(s,'exchange-proof:'+ip(req),20));const proof=await tx(s=>s.get('token',hash(data.token)));if(proof?.passwordHash)assert(await passwords.verify(data.password,proof.passwordHash),'Bitte das bei der Registrierung gewählte Passwort eingeben.',401);return tx(async s=>{await rate(s,'exchange:'+ip(req),30);const token=await s.get('token',hash(data.token));assert(token&&token.expires>Date.now()&&token.id===proof?.id,'Dieser Login-Link ist abgelaufen oder wurde bereits verwendet. Bitte einen neuen anfordern.',401);assert(!token.customer,unavailable,403);const target=await s.get('user',hash(token.email));checkWorkspace(target||{role:token.email===adminEmail?'admin':'partner'});let user=await s.get('user',hash(token.email));if(!user){assert(token.company||token.email===adminEmail,'Zugang nicht vorhanden.',403);let companyId=null;if(token.company){companyId=id();await s.put('company',{...token.company,id:companyId,email:token.email,status:'pending',createdAt:new Date().toISOString(),reviewNote:''});}user={id:hash(token.email),email:token.email,name:token.company?token.company.contact:'UNFALLX Administration',phone:token.company?.phone||'',role:token.email===adminEmail?'admin':'partner',companyId,active:true,passwordHash:token.passwordHash||undefined,termsVersion:token.termsVersion||undefined,createdAt:new Date().toISOString(),verifiedAt:new Date().toISOString()};await s.put('user',user,companyId||'internal');if(token.referralCode)await referrals.attribute(s,user,token.referralCode);}assert(user.active,'Der Zugang ist gesperrt.',403);assertPortalUser(user);if(!user.verifiedAt){user.verifiedAt=new Date().toISOString();await s.put('user',user,user.companyId||'internal');}await s.remove('token',token.id);return issueSession(s,user);});}
 async function invite(user,data,resend=false){
  assert(mail.ready,'Der E-Mail-Versand ist gerade nicht eingerichtet.',503);
  const delivery=await tx(async s=>{await rate(s,'team-invite:'+user.id,20);let member;
   if(resend){member=await s.get('user',text(data.id,128,true));assert(member&&member.role==='appraiser'&&member.active,'Aktiver interner Zugang nicht gefunden.',404);}
   else{const address=email(data.email);assert(!await s.get('user',hash(address)),'Diese E-Mail-Adresse besitzt bereits einen Zugang.');member={id:hash(address),email:address,name:text(data.name,120,true),role:'appraiser',active:true,companyId:null,invitedBy:user.id,invitedAt:new Date().toISOString()};}
   for(const old of await s.list('token',member.email))if(old.purpose==='invitation')await s.remove('token',old.id);
   const token=random();await s.put('token',{id:hash(token),email:member.email,purpose:'invitation',expires:Date.now()+24*hour},member.email);member.invitationStatus='sending';await s.put('user',member,'internal');return {member,token};
  });
  try{const content=accessEmail({kind:'invitation',name:delivery.member.name,url:recipientOrigin(delivery.user||delivery.member)+'/login#token='+delivery.token,origin:recipientOrigin(delivery.user||delivery.member)});await mail.send(delivery.member.email,content.subject,content.text,[],content.html);await tx(async s=>{const member=await s.get('user',delivery.member.id);member.invitationStatus='sent';member.invitationSentAt=new Date().toISOString();await s.put('user',member,'internal');});return {invitationSent:true,message:'Zugang angelegt. Die persönliche Einladung wurde per E-Mail versandt und ist 24 Stunden gültig.'};}
  catch{await tx(async s=>{await s.remove('token',hash(delivery.token));const member=await s.get('user',delivery.member.id);member.invitationStatus='failed';await s.put('user',member,'internal');});return {invitationSent:false,message:'Der Zugang ist angelegt, aber die Einladung konnte nicht versandt werden. Bitte „Einladung erneut senden“ verwenden.'};}
 }
 const autoixpert=require('./autoixpert').createAutoixpert({env,tx,caseAccess,audit});
 const archiveUsers=new Set();
 let uploadsInFlight=0,previewsInFlight=0;const previewQueue=[];
 async function upload(req,user,cid){assert(uploadsInFlight<4,'Der Upload ist gerade ausgelastet. Bitte gleich erneut versuchen.',429);uploadsInFlight++;try{return await uploadFile(req,user,cid);}finally{uploadsInFlight--;}}
 async function uploadFile(req,user,cid){await tx(async s=>{await caseAccess(s,user,cid);await rate(s,'file-upload:'+user.id,200,hour);});const kind=text(req.headers['x-file-kind'],30,true);assert(['photo','document','registration','authorization','case_bundle','report','partner_invoice'].includes(kind),'Ungültige Dateiart.');let name;try{name=decodeURIComponent(req.headers['x-file-name']||'');}catch{throw new Problem(400,'Ungültiger Dateiname.');}name=text(name,180,true).replace(/[\/\\\r\n"<>]/g,'_');const bytes=await body(req,25*1024*1024,true);assert(bytes.length>0,'Die Datei ist leer.');const type=String(req.headers['content-type']||'').split(';')[0];let ext;
 if(['image/jpeg','image/png','image/webp'].includes(type)){try{const meta=await sharp(bytes,{limitInputPixels:60000000}).metadata();const expected={'image/jpeg':'jpeg','image/png':'png','image/webp':'webp'}[type];assert(meta.format===expected&&meta.width>0&&meta.height>0&&!meta.pages,'Ungültiges oder animiertes Bild.');await sharp(bytes,{limitInputPixels:60000000}).resize(1,1).toBuffer();ext=expected==='jpeg'?'jpg':expected;}catch{throw new Problem(400,'Dieses Bild kann nicht gelesen werden. Bitte JPG, PNG oder WebP verwenden.');}}else if(['image/heic','image/heif'].includes(type)&&require('./upload-format').isHeif(bytes)){ext=type==='image/heic'?'heic':'heif';}else if(type==='application/pdf'&&bytes.subarray(0,5).toString()==='%PDF-'&&bytes.subarray(-2048).includes(Buffer.from('%%EOF'))){ext='pdf';}else throw new Problem(415,'Erlaubt sind JPG, PNG, WebP, HEIC/HEIF und PDF.');assert(kind!=='photo'||ext!=='pdf','Für Schadenfotos bitte ein Bild hochladen.');assert(!['report','partner_invoice'].includes(kind)||ext==='pdf','Gutachten und Rechnungen bitte als PDF hochladen.');
 return tx(async s=>{const c=await caseAccess(s,user,cid);assert(c.status!=='closed'&&c.status!=='declined','Dieser Fall ist abgeschlossen.');if(user.role==='partner'){const co=await s.get('company',user.companyId);assert(co.status==='approved','Die Firma muss zuerst freigeschaltet werden.',403);assert(kind!=='report','Gutachten können nur intern hochgeladen werden.',403);if(kind==='partner_invoice'){assert(D.payable(c)&&c.finance.partnerAcceptedAt,'Eine Rechnung ist erst nach bestätigter Vergütung und vollständigem Zahlungseingang möglich.');assert(!c.finance.partnerInvoiceId,'Eine Partnerrechnung liegt bereits vor.');}else assert(['draft','recording','ready_to_submit','needs_info'].includes(c.status),'Weitere Unterlagen bitte im Rahmen einer Rückfrage hochladen.');}else assert(kind!=='partner_invoice','Die Partnerrechnung muss vom Partner eingereicht werden.');
 const files=await s.list('file',cid);const existing=files.find(f=>f.sha256===hash(bytes)&&f.kind===kind&&f.type===type);if(existing)return {file:existing,alreadyStored:true};assert(files.length<100&&files.reduce((n,f)=>n+f.size,0)+bytes.length<=750*1024*1024,'Das Upload-Limit dieses Falls ist erreicht.');const usage=await s.get('system','storage')||{id:'storage',bytes:0};assert(usage.bytes+bytes.length<=storageConfig(env).limit,'Der verfügbare Dokumentenspeicher ist belegt. Bitte UNFALLX kontaktieren.',507);const file={id:id(),caseId:cid,kind,name:name.replace(/\.[^.]+$/,'')+'.'+ext,type,size:bytes.length,sha256:hash(bytes),at:new Date().toISOString(),by:user.name};await s.blob(file.id,bytes);await s.put('file',file,cid);usage.bytes+=bytes.length;await s.put('system',usage);if(kind==='partner_invoice'){c.finance.partnerInvoiceId=file.id;c.finance.partnerInvoiceApproved=false;}await audit(s,user,c,'Datei hochgeladen',file.name);return {file};});}
 async function action(s,user,c,data){assert(data.version===c.version,'Der Fall wurde inzwischen geändert. Bitte neu laden.',409);const a=data.action;
 if(await require('./workflow').apply(s,user,c,data,audit))return {case:D.publicCase(c,user)};
 if(a==='save'){assert(!external(user)||['draft','recording','ready_to_submit','needs_info'].includes(c.status),'Der eingereichte Fall ist schreibgeschützt.',403);const intake=D.intake(data);if(intake.lawyerChoice==='unfallx'){for(const key of ['lawyerName','lawyerEmail','lawyerPhone'])intake[key]=c.lawyerId?c.intake[key]||'':'';}if(c.intake.customerEmail!==intake.customerEmail)c.trackingEpoch=(c.trackingEpoch||0)+1;if(c.intake.lawyerEmail!==intake.lawyerEmail||c.intake.lawyerChoice!==intake.lawyerChoice){c.lawyerId=null;c.lawyerHandoff=null;}c.intake=intake;await audit(s,user,c,'Falldaten aktualisiert');}
 else if(a==='submit'){assert(external(user),'Diese Aktion ist für Einreicher vorgesehen.',403);if(user.role==='partner'){const co=await s.get('company',user.companyId);assert(co.status==='approved','Deine Firma ist noch nicht freigeschaltet.',403);}assert(['draft','recording','ready_to_submit','needs_info'].includes(c.status),'Der Fall wurde bereits eingereicht.');D.validateSubmission(c,await s.list('file',c.id));c.status='submitted';c.submittedAt=c.submittedAt||new Date().toISOString();await audit(s,user,c,'Fall eingereicht');}
 else if(a==='file_kind'){assert(!['closed','declined'].includes(c.status),'Dieser Fall ist abgeschlossen.');assert(!external(user)||['draft','recording','ready_to_submit','needs_info'].includes(c.status),'Der eingereichte Fall ist schreibgeschützt.',403);const file=await s.get('file',text(data.fileId,128,true));assert(file&&file.caseId===c.id,'Datei nicht gefunden.',404);const allowed=['photo','document','registration','authorization','case_bundle'];assert(allowed.includes(file.kind)&&allowed.includes(data.kind),'Diese Dateiart kann nicht geändert werden.');assert(data.kind!=='photo'||file.type.startsWith('image/'),'Ein Schadenfoto muss eine Bilddatei sein.');file.kind=data.kind;await s.put('file',file,c.id);await audit(s,user,c,'Unterlage zugeordnet',file.name);}
 else if(a==='comment'){const note=text(data.note,4000,true);await audit(s,user,c,'Nachricht',note);}
 else if(a==='partner_status'){assert(user.role==='partner','Nur für Partnerbetriebe.',403);assert((await s.get('company',user.companyId))?.status==='approved','Firma ist nicht freigeschaltet.',403);const allowed={draft:['recording'],recording:['draft','ready_to_submit'],ready_to_submit:['recording'],needs_info:['recording']};assert((allowed[c.status]||[]).includes(data.status),'Partner können nur Aufnahme und Vorbereitung aktualisieren.',403);if(data.status==='ready_to_submit')D.validateSubmission(c,await s.list('file',c.id));c.status=data.status;await audit(s,user,c,'Status: '+D.caseStates[c.status]);}
 else if(a==='accept_terms'){assert(user.role==='partner'&&c.finance&&c.finance.agreement&&c.finance.partnerNet>0,'Es liegt noch keine Vergütungsvereinbarung vor.');c.finance.partnerAcceptedAt=new Date().toISOString();await audit(s,user,c,'Vergütung vom Partner bestätigt',c.finance.agreement);}
 else {assert(internal(user),'Nur das UNFALLX-Team darf diese Aktion ausführen.',403);
 if(a==='referral'){isAdmin(user);await referrals.attach(s,c,text(data.referralCode,32,true));await audit(s,user,c,'Empfehlung zugeordnet','',true);}
 else if(a==='lawyer'){assert(c.status!=='closed'&&c.status!=='report_sent','Bei abgeschlossenen Übergaben bleibt der Kanzleikontakt dokumentiert.');await lawyers.assign(s,c,data);await audit(s,user,c,'Kanzlei zugeordnet','',true);}
 else if(a==='tracking_revoke'){isAdmin(user);assert(data.confirmed===true,'Bitte das Sperren bestehender Statuslinks bestätigen.');c.trackingEpoch=(c.trackingEpoch||0)+1;await audit(s,user,c,'Statuslinks aufgehoben','',true);}
 else if(a==='status'){const status=text(data.status,30,true);if(['draft','recording','ready_to_submit'].includes(c.status))isAdmin(user);assert((D.transitions[c.status]||[]).includes(status),'Dieser Statuswechsel ist nicht möglich.');if(status==='submitted')D.validateSubmission(c,await s.list('file',c.id));if(status==='needs_info')assert(text(data.note,4000,true),'Bitte die Rückfrage beschreiben.');if(status==='report_ready')assert((await s.list('file',c.id)).some(f=>f.kind==='report'),'Bitte zuerst das fertige Gutachten als PDF hochladen.');if(status==='report_sent'&&c.intake.lawyerEmail){assert(c.intake.shareWithLawyer,'Bitte die autorisierte Kanzleiübermittlung bestätigen.');c.lawyerHandoff=await lawyers.snapshot(s,c);}if(status==='report_sent')assert(data.confirmed===true&&text(data.reference,300,true),'Bitte Versand mit Empfänger und Versanddatum dokumentieren.');if(status==='closed')assert(!c.finance?.partnerNet||c.finance.paidOutAt,'Bitte erst die Partnerabrechnung abschließen.');c.status=status;if(status==='submitted')c.submittedAt=c.submittedAt||new Date().toISOString();if(status==='report_ready')c.reportReadyAt=c.reportReadyAt||new Date().toISOString();await audit(s,user,c,'Status: '+D.caseStates[status],text(data.note||data.reference,4000));}
 else if(a==='assign'){isAdmin(user);const member=await s.get('user',text(data.assignee,128,true));assert(member&&member.active&&['admin','appraiser'].includes(member.role),'Bitte einen aktiven internen Bearbeiter auswählen.');c.assignee=member.id;await audit(s,user,c,'Bearbeiter zugewiesen',member.name,true);}
 else if(a==='finance'){isAdmin(user);assert(!c.finance?.partnerInvoiceId&&!c.finance?.paidOutAt,'Nach Eingang der Partnerrechnung sind die vereinbarten Beträge gesperrt.');const old=c.finance||{};let calculated=null;if(data.calculation){try{calculated=financeMath.calculate(data.calculation);}catch(e){throw new Problem(400,e.message);}}const net=calculated?calculated.invoiceNet:D.money(data.invoiceNet),gross=calculated?calculated.invoiceGross:D.money(data.invoiceGross),partner=calculated?calculated.partnerNet:D.money(data.partnerNet);assert(c.companyId||partner===0,'Partnervergütung ist für Firmenfälle vorgesehen.');assert(gross>=net&&net>0&&partner<=net,'Bitte plausible Gutachten- und Partnerbeträge eingeben.');const agreement=text(data.agreement,1000,!!partner);c.finance={...old,...(calculated||{}),invoiceNet:net,invoiceGross:gross,invoiceNumber:text(data.invoiceNumber,100,true),partnerNet:partner,agreement,agreedAt:new Date().toISOString(),received:old.received||0,partnerAcceptedAt:old.partnerNet===partner&&old.agreement===agreement?old.partnerAcceptedAt:null};assert(c.finance.received<=gross,'Bereits erfasste Zahlung übersteigt den Rechnungsbetrag.');await audit(s,user,c,'Vergütung zur Bestätigung hinterlegt',agreement);}
 else if(a==='payment'){isAdmin(user);assert(c.finance?.invoiceGross&&!c.finance.paidOutAt,'Bitte zuerst die Rechnungsdaten erfassen.');const cents=D.money(data.amount);assert(cents>0&&c.finance.received+cents<=c.finance.invoiceGross,'Zahlung übersteigt den offenen Rechnungsbetrag.');const reference=text(data.reference,300,true);const paidDate=D.date(data.date);c.finance.received+=cents;await s.put('payment',{id:id(),caseId:c.id,cents,date:paidDate,reference,actor:user.name,at:new Date().toISOString()},c.id);await audit(s,user,c,'Zahlungseingang erfasst',reference,true);}
 else if(a==='approve_invoice'){isAdmin(user);assert(D.payable(c)&&c.finance.partnerAcceptedAt&&c.finance.partnerInvoiceId,'Die Partnerrechnung ist noch nicht freigabefähig.');assert(data.confirmed===true,'Bitte die Rechnungsprüfung bestätigen.');c.finance.partnerInvoiceApproved=true;c.finance.approvedBy=user.id;await audit(s,user,c,'Partnerrechnung freigegeben');}
 else if(a==='payout'){isAdmin(user);assert(D.payable(c)&&c.finance.partnerInvoiceApproved&&!c.finance.paidOutAt,'Die Auszahlung ist noch nicht freigegeben oder bereits erfasst.');assert(data.confirmed===true,'Bitte die erfolgte Banküberweisung bestätigen.');c.finance.paidOutAt=D.date(data.date);c.finance.payoutReference=text(data.reference,300,true);await audit(s,user,c,'Auszahlung erfasst',c.finance.payoutReference);}
 else if(a==='internal_note'){c.internalNote=text(data.note,8000);await audit(s,user,c,'Interne Notiz aktualisiert','',true);}
 else throw new Problem(400,'Unbekannte Aktion.');
 }return {case:D.publicCase(c,user)};}
 async function dispatch(req,user,cid,data){assert(internal(user),'Nur UNFALLX kann Dokumente versenden.',403);assert(data.confirmed===true,'Bitte den Versand bestätigen.');let payload;await tx(async s=>{const c=await caseAccess(s,user,cid);assert(c.version===data.version,'Fall geändert. Bitte neu laden.',409);assert(c.status==='report_ready'&&c.intake.shareWithLawyer&&c.intake.lawyerEmail,'Bitte Gutachten freigeben und eine autorisierte Kanzlei hinterlegen.');assert(!c.dispatch||c.dispatch.state==='failed','Dieser Versand wurde bereits ausgelöst.');const file=await s.get('file',text(data.fileId,128,true));assert(file&&file.caseId===cid&&file.kind==='report','Gutachten nicht gefunden.');const lawyer=await lawyers.snapshot(s,c);payload={lawyer,to:c.intake.lawyerEmail,name:file.name,bytes:await s.blob(file.id),number:c.number};c.dispatch={state:'sending',at:new Date().toISOString()};await audit(s,user,c,'Kanzleiversand gestartet',payload.to,true);});
 try{await mail.send(payload.to,'UNFALLX Gutachten · '+payload.number,`Guten Tag,\n\nanbei erhalten Sie das freigegebene Gutachten zum Vorgang ${payload.number} im Rahmen des vorliegenden Auftrags.\n\nFür Rückfragen: info@unfallx.com\nUNFALLX · Unext GmbH`,[{filename:payload.name,content:payload.bytes,contentType:'application/pdf'}]);}catch{await tx(async s=>{const c=await caseAccess(s,user,cid);c.dispatch.state='failed';await audit(s,user,c,'Kanzleiversand fehlgeschlagen','Bitte Empfänger prüfen und erneut versuchen.',true);});throw new Problem(503,'Die E-Mail konnte nicht bestätigt werden. Bitte den Versandstatus vor einem erneuten Versand prüfen.');}
 return tx(async s=>{const c=await caseAccess(s,user,cid);c.dispatch={state:'sent',at:new Date().toISOString(),to:payload.to};c.status='report_sent';c.lawyerHandoff=payload.lawyer;await audit(s,user,c,'Gutachten an Kanzlei versandt');return {case:D.publicCase(c,user)};});}
 const mobileIntake=require('./mobile-intake').createMobileIntake({tx,body,rate,ip,env,onSubmitted:(s,user,c,event)=>notifications.event(s,user,c,event),authorize:req=>tx(async s=>{const {user}=await auth(req,s);return {user,company:user.companyId?await s.get('company',user.companyId):null};})});
 const referrals=createReferrals({tx,rate,origin});
 const tracking=createTracking({tx,rate,origin});
 const documents=createDocuments({tx,body,env,rate});
 const lawyers=createLawyers({tx,rate,mail,origin,body});
 const notifications=createNotifications({tx,mail,origin,rate,tracking,recipientOrigin:user=>local&&!scope().production?origin:internal(user)?hosts.ADMIN_ORIGIN:hosts.APP_ORIGIN});
 const security=createSecurity({env,tx,rate,mail,origin,recipientOrigin,...(options.sms?{sms:options.sms}:{})});
 const oauth=createOAuth({env,origin,tx,rate,ip,body,auth,issueSession,mail,referrals,requestOrigin,checkWorkspace});
 async function route(req,res,url){
 assert(!hosts.educationApi(url.pathname),'Dieser Bereich ist nicht mehr verfügbar.',410);
 assert(local||scope().workspace,'Bitte den passenden UNFALLX-Portalzugang öffnen.',403);
 const path=url.pathname.replace('/api/portal','');
 if(path.startsWith('/mobile/')){assert(scope().workspace==='partner'||local&&!scope().production,'Kundenaufnahmen nur im App-Bereich.',403);assert(!req.headers.origin||req.headers.origin===requestOrigin(),'Anfrageherkunft nicht erlaubt.',403);return mobileIntake.route(path,req);}
 if(/^\/oauth\/(google|apple)\/callback$/.test(path)&&['GET','POST'].includes(req.method))return oauth.route(path,req,res,url);
 if(req.method==='POST')assert(req.headers.origin===requestOrigin(),'Anfrageherkunft nicht erlaubt.',403);
 assert(['GET','POST'].includes(req.method),'Methode nicht erlaubt.',405);
 if(path==='/tracking'&&req.method==='POST')return tracking.read(await body(req),ip(req));
 if(path==='/lawyers/register'&&req.method==='POST')return lawyers.register(req,await body(req),ip(req));
 if(path==='/lawyers/verify'&&req.method==='POST')return lawyers.verify(await body(req),ip(req));
 const logoPath=path.match(/^\/lawyers\/logos\/([a-f0-9-]{36})$/);if(logoPath&&req.method==='GET'){const bytes=await lawyers.image(logoPath[1]);res.setHeader('Content-Type','image/webp');res.end(bytes);return null;}
 if(path.startsWith('/oauth/'))return oauth.route(path,req,res,url);
 if(path==='/notifications/verify'&&req.method==='POST')return notifications.verify(req,await body(req),ip(req));
 if(path==='/security/config'&&req.method==='GET')return {smsAvailable:security.ready};
 if(path.startsWith('/security/login')){
  const {user,session}=await tx(s=>auth(req,s,true));assert(session.pendingMfa,'Bitte zuerst mit deinem Passwort anmelden.',401);
  if(path==='/security/login'&&req.method==='GET')return tx(async s=>({csrf:session.csrf,security:await security.view(s,user)}));
  if(path==='/security/login/send'&&req.method==='POST')return security.start(user,session,{},'login');
  if(path==='/security/login/verify'&&req.method==='POST'){
   const data=await body(req);await tx(s=>rate(s,'mfa-check:'+user.id,25,15*60000));
   const result=await tx(async s=>{const fresh=await s.get('user',user.id),current=await s.get('session',session.id);await enabled(s,fresh);assert(current&&current.expires>Date.now(),'Bitte erneut anmelden.',401);const proof=await security.loginCheck(s,fresh,current,data);if(!proof.ok)return proof;await s.remove('session',current.id);for(const c of await s.list('sms_challenge',user.id))if(c.sessionId===current.id)await s.remove('sms_challenge',c.id);return {ok:true,...await issueSession(s,fresh,proof)};});
   assert(result.ok,result.error,401);res.setHeader('Set-Cookie',result.cookie);delete result.cookie;return result;
  }
  throw new Problem(404,'Nicht gefunden.');
 }
 if(path==='/password-login'&&req.method==='POST'){const result=await passwordLogin(req,await body(req));res.setHeader('Set-Cookie',result.cookie);delete result.cookie;return result;}
 if(path==='/password/request'&&req.method==='POST')return passwordReset(req,await body(req));
 if(path==='/password/finish'&&req.method==='POST')return finishPassword(req,await body(req));
 if(path==='/token-info'&&req.method==='POST'){const data=await body(req);assert(/^[a-f0-9]{64}$/.test(data.token||''),'Ungültiger Link.');return tx(async s=>{await rate(s,'token-info:'+ip(req),30);const token=await s.get('token',hash(data.token));assert(token&&token.expires>Date.now(),'Dieser Link ist abgelaufen oder wurde bereits verwendet.',401);return {passwordRequired:!!token.passwordHash};});}
 if(path==='/login'&&req.method==='POST')return loginRequest(req,await body(req),false);
 if(path==='/register'&&req.method==='POST')return loginRequest(req,await body(req),true);
 if(path==='/exchange'&&req.method==='POST'){const result=await exchange(req,await body(req));res.setHeader('Set-Cookie',result.cookie);delete result.cookie;return result;}
 if(path==='/register-customer'&&req.method==='POST')throw new Problem(410,unavailable);
 const {user,session}=await tx(s=>auth(req,s));
 if(path==='/security'&&req.method==='GET')return tx(async s=>({security:await security.view(s,user),recoveryLogin:!!session.recoveryLogin}));
 if(path==='/security/phone/send'&&req.method==='POST')return security.start(user,session,await body(req));
 if(path==='/security/phone/verify'&&req.method==='POST'){await tx(s=>rate(s,'phone-check:'+user.id,25,15*60000));return security.verify(user,session,await body(req));}
 if(path==='/security/configure'&&req.method==='POST')return security.configure(user,session,await body(req));
 if(path==='/documents'&&req.method==='GET')return documents.overview(user);
 if(path==='/documents'&&req.method==='POST')return documents.upload(req,user);
 const documentPath=path.match(/^\/documents\/([a-f0-9-]{36})$/);if(documentPath&&req.method==='GET'){const r=await documents.download(user,documentPath[1]);assert(r.bytes,'PDF nicht gefunden.',404);res.writeHead(200,{'Content-Type':'application/pdf','Content-Disposition':"attachment; filename*=UTF-8''"+encodeURIComponent(r.file.name),'Content-Security-Policy':"default-src 'none'; sandbox"});res.end(r.bytes);return null;}
 if(path==='/statistics'&&req.method==='GET')return tx(async s=>statistics((await s.list('case')).filter(c=>visible(user,c)),user));
 if(path==='/referrals'&&req.method==='GET')return referrals.overview(user);
 if(path==='/referrals/join'&&req.method==='POST')return referrals.join(user,await body(req));
 if(path==='/referrals/accept'&&req.method==='POST')return referrals.accept(user,await body(req));
 if(path==='/identities'&&req.method==='GET')return tx(async s=>({providers:oauth.config(),linked:(await s.list('identity',user.id)).map(i=>i.provider)}));
 if(path==='/identities/unlink'&&req.method==='POST'){const data=await body(req);return tx(async s=>{const fresh=await s.get('user',user.id),ids=await s.list('identity',user.id);assert(Date.now()-Date.parse(session.createdAt)<15*60000,'Bitte zuerst erneut anmelden.',401);assert(fresh.passwordHash||ids.length>1,'Bitte zuerst ein Passwort festlegen.');for(const i of ids)if(i.provider===data.provider)await s.remove('identity',i.id);return {message:'Anmeldemethode getrennt.'};});}
 if(path==='/me'&&req.method==='GET')return tx(async s=>({user:publicUser(user),csrf:session.csrf,company:user.companyId?await s.get('company',user.companyId):null,states:D.caseStates}));
 if(path==='/logout'&&req.method==='POST'){await tx(s=>s.remove('session',session.id));res.setHeader('Set-Cookie',sessionCookie('',0));return {ok:true};}
 if(path==='/settings'&&req.method==='GET')return tx(async s=>({profile:{name:user.name,phone:user.phone||'',jobTitle:user.jobTitle||'',email:user.email},preferences:user.preferences||{startPage:'start',compact:false,reducedMotion:false,theme:'light'},activeSessions:(await s.list('session',user.id)).filter(x=>x.expires>Date.now()).length,storage:user.role==='admin'?{backend:storageConfig(env).backend,used:(await s.get('system','storage'))?.bytes||0,limit:storageConfig(env).limit}:null}));
 if(path==='/settings'&&req.method==='POST'){const data=await body(req);return tx(async s=>{const fresh=await s.get('user',user.id);const name=text(data.name,120,true),phone=text(data.phone,40),jobTitle=text(data.jobTitle,100);assert(['start','faelle'].includes(data.startPage),'Bitte eine gültige Startansicht wählen.');assert(typeof data.compact==='boolean'&&typeof data.reducedMotion==='boolean','Ungültige Anzeigeeinstellung.');assert(['light','dark'].includes(data.theme),'Bitte eine gültige Darstellung wählen.');await security.changePhone(s,fresh,phone);fresh.name=name;fresh.phone=phone;fresh.jobTitle=jobTitle;fresh.preferences={caseEmails:data.caseEmails!==false,startPage:data.startPage,compact:data.compact,reducedMotion:data.reducedMotion,theme:'light'};await s.put('user',fresh,fresh.companyId||'internal');return {user:publicUser(fresh),message:'Deine Einstellungen wurden gespeichert.'};});}
 if(path==='/sessions/revoke-others'&&req.method==='POST'){const data=await body(req);assert(data.confirmed===true,'Bitte Abmeldung der anderen Geräte bestätigen.');return tx(async s=>{let count=0;for(const other of await s.list('session',user.id))if(other.id!==session.id){await s.remove('session',other.id);count++;}return {message:'Andere Sitzungen wurden abgemeldet.',revoked:count};});}
 if(path==='/cases'&&req.method==='GET')return tx(async s=>{const listing=await caseFolders.listing(s,user,(await s.list('case',user.role==='partner'?user.companyId:undefined)).filter(c=>visible(user,c)),url.searchParams.get('folder')||'active');return {...listing,cases:(await require('./presentation').summarizeCases(s,listing.cases,user)).map(c=>D.publicCase(c,user))};});
 const filing=path.match(/^\/cases\/([a-f0-9-]{36})\/filing$/);
 if(filing&&req.method==='POST'){const data=await body(req);return tx(async s=>{const c=await caseAccess(s,user,filing[1]);await rate(s,'case-filing:'+user.id,120);return caseFolders.change(s,user,c,data);});}
 if(path==='/messages'&&req.method==='GET')return tx(async s=>{const messages=[];for(const c of (await s.list('case',user.role==='partner'?user.companyId:undefined)).filter(c=>visible(user,c))){for(const e of await s.list('event',c.id))if(!e.internal&&e.action==='Nachricht')messages.push({id:e.id,caseId:c.id,caseNumber:c.number,vehicle:c.intake.vehicle||'',plate:c.intake.plate||'',actor:e.actor,note:e.note||'',at:e.at});}return {messages:messages.sort((a,b)=>b.at.localeCompare(a.at)).slice(0,100)};});
 if(path==='/cases'&&req.method==='POST'){const data=await body(req);return tx(async s=>{assert(external(user)||user.role==='admin','Nur Administration und Einreicher können Fälle anlegen.',403);const companyId=user.role==='admin'?text(data.companyId,128)||null:user.companyId;const co=companyId?await s.get('company',companyId):null;if(user.role==='admin'&&companyId)assert(co?.status==='approved','Bitte freigeschalteten Partner wählen.');if(user.role==='partner')assert(co?.status==='approved','Deine Firma ist noch nicht freigeschaltet.',403);const requestId=text(data.requestId,64);assert(!requestId||/^[a-f0-9-]{36}$/.test(requestId),'Ungültige Entwurfskennung.');const requestKey=requestId?hash(user.id+':'+requestId):null;if(requestKey){const previous=await s.get('case_request',requestKey);if(previous)return {case:D.publicCase(await caseAccess(s,user,previous.caseId),user)};}await rate(s,'new-case:'+(user.companyId||user.id),25,24*hour);const c={id:id(),number:'UX-'+new Date().getUTCFullYear()+'-'+random().slice(0,8).toUpperCase(),companyId:companyId||null,ownerUserId:null,source:user.role==='admin'?'internal':'partner',companyName:co?.name||'Direktauftrag von UNFALLX',status:'draft',version:0,intake:D.intake(data),assignee:null,createdAt:new Date().toISOString(),finance:null};if(c.intake.lawyerChoice==='unfallx')for(const key of ['lawyerName','lawyerEmail','lawyerPhone'])c.intake[key]='';assert(c.intake.vehicle||c.intake.plate||c.intake.owner,'Bitte für den Entwurf mindestens Fahrzeug, Kennzeichen oder Auftraggeber angeben.');if(user.role==='admin')await referrals.attach(s,c,data.referralCode);await audit(s,user,c,c.status==='submitted'?'Fall eingereicht':'Fall angelegt');if(requestKey)await s.put('case_request',{id:requestKey,caseId:c.id},user.id);return {case:D.publicCase(c,user)};});}
 const ax=path.match(/^\/cases\/([a-f0-9-]{36})\/autoixpert$/);
 if(ax){if(req.method==='GET')return autoixpert.state(user,ax[1]);if(req.method==='POST')return autoixpert.step(user,ax[1],await body(req));}
 const handover=path.match(/^\/cases\/([a-f0-9-]{36})\/handover$/);
 if(handover&&req.method==='GET'){assert(internal(user),'Nur intern verfügbar.',403);const payload=await tx(async s=>{const c=await caseAccess(s,user,handover[1]);return require('./handover').handover(c,await s.list('file',c.id));});res.setHeader('Content-Disposition','attachment; filename="UNFALLX-Fallakte.json"');return payload;}
 const archive=path.match(/^\/cases\/([a-f0-9-]{36})\/archive$/);
 if(archive&&req.method==='GET'){
  const selection=url.searchParams.get('scope')||'photos';assert(['photos','all'].includes(selection),'Bitte Fotos oder alle Unterlagen auswählen.');
  assert(archiveUsers.size<2&&!archiveUsers.has(user.id),'Ein Sammeldownload läuft bereits. Bitte kurz warten.',429);archiveUsers.add(user.id);
  try{
   const allowed=(f,c,u=user)=>(u.role!=='appraiser'||f.kind!=='partner_invoice')&&(!external(u)||f.kind!=='report'||['report_ready','report_sent','closed'].includes(c.status))&&(selection==='all'||f.kind==='photo');
   const result=await tx(async s=>{const c=await caseAccess(s,user,archive[1]);await rate(s,'file-archive:'+user.id,30,hour);return {c,files:(await s.list('file',c.id)).filter(f=>allowed(f,c)).sort((a,b)=>String(a.at).localeCompare(String(b.at))||a.id.localeCompare(b.id))};});
   await sendArchive(res,result.files,f=>tx(async s=>{const fresh=(await auth(req,s)).user,c=await caseAccess(s,fresh,archive[1]),file=await s.get('file',f.id);assert(file&&file.caseId===c.id&&allowed(file,c,fresh)&&file.sha256===f.sha256,'Datei nicht mehr verfügbar.',404);return s.blob(f.id);}),result.c.number.replace(/[^A-Za-z0-9_-]/g,'_')+'-'+(selection==='photos'?'Fotos':'Unterlagen')+'.zip');
   return null;
  }finally{archiveUsers.delete(user.id);}
 }
 let m=path.match(/^\/cases\/([a-f0-9-]{36})(\/files|\/dispatch)?$/);
 if(m){const cid=m[1];if(m[2]==='/files'&&req.method==='POST')return upload(req,user,cid);if(m[2]==='/dispatch'&&req.method==='POST')return dispatch(req,user,cid,await body(req));if(!m[2]&&req.method==='POST'){const data=await body(req);return tx(async s=>action(s,user,await caseAccess(s,user,cid),data));}if(!m[2]&&req.method==='GET')return tx(async s=>{const c=await caseAccess(s,user,cid);return {case:{...D.publicCase(c,user),filing:await caseFolders.read(s,user,cid)},files:(await s.list('file',cid)).filter(f=>(user.role!=='appraiser'||f.kind!=='partner_invoice')&&(!external(user)||f.kind!=='report'||['report_ready','report_sent','closed'].includes(c.status))).sort((a,b)=>String(a.at).localeCompare(String(b.at))||a.id.localeCompare(b.id)),events:(await s.list('event',cid)).filter(e=>!external(user)||!e.internal).sort((a,b)=>a.at.localeCompare(b.at)),payments:user.role==='admin'?await s.list('payment',cid):[]};});}
 m=path.match(/^\/files\/([a-f0-9-]{36})(\/(?:preview|thumbnail))?$/);if(m&&req.method==='GET'){
 const file=await tx(async s=>{const f=await s.get('file',m[1]);assert(f,'Datei nicht gefunden.',404);const c=await caseAccess(s,user,f.caseId);assert(user.role!=='appraiser'||f.kind!=='partner_invoice','Datei nicht gefunden.',404);assert(!external(user)||f.kind!=='report'||['report_ready','report_sent','closed'].includes(c.status),'Gutachten noch nicht freigegeben.',403);return f;});
 if(m[2]){
  assert(['image/jpeg','image/png','image/webp'].includes(file.type),'Für diese Datei ist keine Bildvorschau verfügbar.',415);
  assert(previewQueue.length<32,'Zu viele gleichzeitige Vorschauen. Bitte erneut laden.',429);
  if(previewsInFlight>=4)await new Promise(resolve=>previewQueue.push(resolve));else previewsInFlight++;
  try{const original=await tx(s=>s.blob(file.id));assert(original,'Datei nicht gefunden.',404);const bytes=await sharp(original,{limitInputPixels:60000000}).rotate().resize({width:m[2]==='/thumbnail'?320:960,height:m[2]==='/thumbnail'?240:720,fit:'inside',withoutEnlargement:true}).webp({quality:78}).toBuffer();res.writeHead(200,{'Content-Type':'image/webp','Content-Length':bytes.length,'Content-Disposition':'inline','X-Content-Type-Options':'nosniff'});res.end(bytes);return null;}
  finally{const next=previewQueue.shift();if(next)next();else previewsInFlight--;}
 }
 const bytes=await tx(s=>s.blob(file.id));assert(bytes,'Datei nicht gefunden.',404);res.writeHead(200,{'Content-Type':file.type,'Content-Disposition':`attachment; filename="UNFALLX-${file.id}.${file.type==='application/pdf'?'pdf':file.type.split('/')[1]}"; filename*=UTF-8''${encodeURIComponent(file.name)}`,'Content-Length':bytes.length,'Content-Security-Policy':"default-src 'none'; sandbox"});res.end(bytes);return null;
 }
 if(path==='/profile'&&req.method==='POST'){const data=await body(req);return tx(async s=>{assert(user.role==='partner','Nur für Firmenkonten.',403);const co=await s.get('company',user.companyId);co.request=text(data.request,4000,true);co.requestedAt=new Date().toISOString();await s.put('company',co);return {message:'Deine Anfrage wurde an die Administration übermittelt.'};});}
 if(path==='/export'&&req.method==='GET')return tx(async s=>({exportedAt:new Date().toISOString(),user:publicUser(user),company:user.companyId?await s.get('company',user.companyId):null,cases:(await s.list('case',user.role==='partner'?user.companyId:undefined)).filter(c=>visible(user,c)).map(c=>D.publicCase(c,user))}));
 if(path.startsWith('/admin/')){isAdmin(user);
 if(path==='/admin/storage'&&req.method==='GET')return storageAdmin.overview();
 if(path==='/admin/storage/check'&&req.method==='POST')return storageAdmin.check(user);
 if(path==='/admin/storage/migrate'&&req.method==='POST')return storageAdmin.migrate(user,await body(req));
 if(path==='/admin/lawyers'&&req.method==='GET')return lawyers.overview();
 if(path==='/admin/lawyers'&&req.method==='POST')return lawyers.save(user,await body(req));
 const lawLogo=path.match(/^\/admin\/lawyers\/([a-f0-9-]{36})\/logo$/);if(lawLogo&&req.method==='POST')return lawyers.logo(req,user,lawLogo[1]);
 if(path==='/admin/referrals'&&req.method==='GET')return referrals.adminOverview();
 if(path==='/admin/referrals'&&req.method==='POST')return referrals.adminAction(user,await body(req));
 if(path==='/admin/notifications'&&req.method==='GET')return notifications.overview();
 if(path==='/admin/notifications/retry'&&req.method==='POST')return notifications.retry(await body(req),user);
 if(path==='/admin/auth-status'&&req.method==='GET')return {providers:oauth.config(),callbacks:{google:requestOrigin()+'/api/portal/oauth/google/callback',apple:requestOrigin()+'/api/portal/oauth/apple/callback'}};
 if(path==='/admin/overview'&&req.method==='GET')return tx(async s=>({companies:await s.list('company'),team:(await s.list('user')).filter(u=>internal(u)).map(publicUser),storage:await s.get('system','storage')}));
 if(path==='/admin/company'&&req.method==='POST'){const data=await body(req);return tx(async s=>{const co=await s.get('company',text(data.id,128,true));assert(co,'Firma nicht gefunden.',404);assert(['approved','rejected','suspended','pending'].includes(data.status),'Ungültiger Status.');co.status=data.status;co.reviewNote=text(data.note,2000);co.reviewedBy=user.id;co.reviewedAt=new Date().toISOString();await s.put('company',co);await s.put('admin_event',{id:id(),action:'Firma '+co.name+': '+co.status,actor:user.id,at:co.reviewedAt});return {company:co};});}
 if(path==='/admin/invite'&&req.method==='POST')return invite(user,await body(req));
 if(path==='/admin/resend-invitation'&&req.method==='POST')return invite(user,await body(req),true);
 if(path==='/admin/team'&&req.method==='POST'){const data=await body(req);return tx(async s=>{const member=await s.get('user',text(data.id,128,true));assert(member&&member.role==='appraiser','Nur interne Mitarbeiterzugänge können hier gesperrt werden.');member.active=data.active===true;await s.put('user',member,'internal');for(const session of await s.list('session',member.id))await s.remove('session',session.id);return {ok:true};});}
 }
 throw new Problem(404,'Nicht gefunden.');
 }
 async function handleScoped(req,res,headers){for(const [k,v]of Object.entries(headers))res.setHeader(k,v);res.setHeader('Cache-Control','private, no-store, max-age=0');res.setHeader('Pragma','no-cache');res.setHeader('CDN-Cache-Control','no-store');res.setHeader('Referrer-Policy','no-referrer');res.setHeader('X-Robots-Tag','noindex, nofollow');try{const result=await route(req,res,new URL(req.url,origin));if(result!==null){res.setHeader('Content-Type','application/json; charset=utf-8');res.end(JSON.stringify(result));}void notifications.flush();}catch(e){if(!res.headersSent){res.statusCode=e.status||500;res.setHeader('Content-Type','application/json; charset=utf-8');res.end(JSON.stringify({error:e.status?e.message:'Die Aktion konnte nicht gespeichert werden. Bitte erneut versuchen.',...(e.status===400&&e.fields?{fields:e.fields}:{})}));}else res.end();if(!e.status)console.error('Portal request failed:',e.code||e.name);}}
 function handle(req,res,headers={}){if(hosts.isRetiredHost(req.headers.host)){res.writeHead(410,{...headers,'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify({error:'Die separate Aufnahme-App wurde eingestellt. Bitte im Partnerportal unter app.unfallx.com anmelden.',redirect:hosts.APP_ORIGIN+'/login'}));return;}const workspace=hosts.workspaceForHost(req.headers.host)||(local?env.PORTAL_PREVIEW_WORKSPACE:null);const production=!!hosts.workspaceForHost(req.headers.host);return context.run({workspace,production,origin:production?hosts.workspaces[workspace].origin:origin},()=>handleScoped(req,res,headers));}
 const notificationTimer=setInterval(()=>{if(database)void notifications.flush();},30000);notificationTimer.unref();
 const cleanupTimer=setInterval(()=>{if(database)tx(cleanup).catch(()=>{});},hour);cleanupTimer.unref();
 return {handle,status:()=>({database:database?'ready':'pending',mail:mail.ready}),ready:db,close:async()=>{clearInterval(cleanupTimer);clearInterval(notificationTimer);if(database)await database.close();}};
}
module.exports={createPortal};
