'use strict';
const D=require('./domain');
const {createStore}=require('./store');
const {createMailer}=require('./mail');
const sharp=require('sharp');
const {accessEmail}=require('./email-templates');
const {assert,text,email,id,hash,random,Problem}=D;
const hour=3600000;
function createPortal(options={}) {
 const env=options.env||process.env;
 const local=env.NODE_ENV==='test';
 const origin=env.PORTAL_ORIGIN||'https://unfallx.com';
 const cookieName=local?'ux_session':'__Host-ux_session';
 const adminEmail=email(env.PORTAL_ADMIN_EMAIL||'info@unfallx.com');
 const mail=options.mail||createMailer(env);
 let database=null,starting=null,lastFailure=0;
 async function db(){if(database)return database;if(Date.now()-lastFailure<15000)throw new Problem(503,'Das Portal wird gerade vorbereitet. Bitte in wenigen Minuten erneut versuchen.');if(!starting)starting=(options.store?Promise.resolve(options.store):createStore(env)).then(async s=>{const probe=id(),bytes=Buffer.from('UNFALLX storage probe');await s.transaction(async q=>{await q.put('probe',{id:probe,value:'ok'});await q.blob(probe,bytes);});await s.transaction(async q=>{const row=await q.get('probe',probe),saved=await q.blob(probe);if(row?.value!=='ok'||!saved?.equals(bytes))throw new Error('DATABASE_INTEGRITY');await q.remove('probe',probe);await q.removeBlob(probe);});return database=s;}).catch(e=>{lastFailure=Date.now();console.error('Portal database unavailable:',e.code||'configuration');throw new Problem(503,'Das Portal ist vorübergehend nicht erreichbar. Bitte später erneut versuchen.');}).finally(()=>{starting=null;});return starting;}
 const tx=async fn=>(await db()).transaction(fn);
 function sessionCookie(value,maxAge=43200){return `${cookieName}=${value}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${maxAge}${local?'':'; Secure'}`;}
 async function body(req,max=40000,raw=false){assert(Number(req.headers['content-length']||0)<=max,'Datei oder Eingabe ist zu groß.',413);if(!raw)assert((req.headers['content-type']||'').split(';')[0]==='application/json','JSON erwartet.',415);const chunks=[];let bytes=0;for await(const chunk of req){bytes+=chunk.length;assert(bytes<=max,'Datei oder Eingabe ist zu groß.',413);chunks.push(chunk);}const b=Buffer.concat(chunks);if(raw)return b;try{return JSON.parse(b.toString('utf8'));}catch{throw new Problem(400,'Ungültige Eingabe.');}}
 async function rate(s,key,max,window=hour){const stamp=Math.floor(Date.now()/window);const rid=hash(key+':'+stamp);let r=await s.get('limit',rid)||{id:rid,count:0,expires:(stamp+2)*window};assert(r.count<max,'Zu viele Versuche. Bitte später erneut versuchen.',429);r.count++;await s.put('limit',r);}
 async function auth(req,s){const cookie=(req.headers.cookie||'').split(';').map(v=>v.trim()).find(v=>v.startsWith(cookieName+'='));assert(cookie,'Bitte anmelden.',401);const token=cookie.slice(cookieName.length+1);assert(/^[a-f0-9]{64}$/.test(token),'Bitte erneut anmelden.',401);const session=await s.get('session',hash(token));assert(session&&session.expires>Date.now(),'Deine Sitzung ist abgelaufen. Bitte erneut anmelden.',401);const user=await s.get('user',session.userId);assert(user&&user.active,'Der Zugang ist gesperrt.',403);if(user.role==='partner'){const company=await s.get('company',user.companyId);assert(company&&company.status!=='suspended','Der Firmenzugang ist gesperrt.',403);}if(req.method!=='GET')assert(req.headers['x-csrf-token']===session.csrf,'Bitte die Seite neu laden.',403);return {user,session};}
 const isAdmin=u=>assert(u.role==='admin','Nur die Administration darf diese Aktion ausführen.',403);
 async function caseAccess(s,user,cid){const c=await s.get('case',cid);assert(c&&(user.role==='admin'||user.role==='partner'&&c.companyId===user.companyId||user.role==='appraiser'&&c.assignee===user.id),'Fall nicht gefunden.',404);return c;}
 async function audit(s,user,c,action,note='',internal=false){await s.put('event',{id:id(),caseId:c.id,actor:user.name,action,note,internal,at:new Date().toISOString()},c.id);c.updatedAt=new Date().toISOString();c.version++;await s.put('case',c,c.companyId);}
 async function cleanup(s){for(const kind of ['token','session','limit'])for(const r of await s.list(kind))if(r.expires<Date.now())await s.remove(kind,r.id);}
 async function loginRequest(req,data,register){assert(mail.ready,'Der E-Mail-Login ist vorübergehend nicht verfügbar.',503);const address=email(data.email);const company=register?D.companyData(data):null;if(register)assert(data.privacy===true,'Bitte die Datenschutzhinweise bestätigen.');let delivery;
 await tx(async s=>{await rate(s,'auth-ip:'+ip(req),15);await rate(s,'auth-email:'+address,4);await rate(s,'auth-global',120);await cleanup(s);const user=await s.get('user',hash(address));if(!register&&!user&&address!==adminEmail)return;if(user&&!user.active)return;const token=random();const record={id:hash(token),email:address,company:!user&&address!==adminEmail?company:null,expires:Date.now()+15*60000};await s.put('token',record,address);delivery={to:address,token};});
 if(delivery)try{const content=accessEmail({kind:register?'registration':'login',name:company?.contact||'',company:company?.name||'',url:origin+'/login#token='+delivery.token,origin});await mail.send(delivery.to,content.subject,content.text,[],content.html);}catch{await tx(s=>s.remove('token',hash(delivery.token)));throw new Problem(503,'Der Login-Link konnte gerade nicht versandt werden. Bitte später erneut versuchen.');}
 return {message:'Wenn die Adresse für diesen Zugang verfügbar ist, erhältst du einen Login-Link. Bitte auch den Spamordner prüfen.'};}
 function ip(req){ // Hostinger terminates TLS; trust only its nearest forwarded hop when explicitly configured.
 const forwarded=env.PORTAL_TRUST_PROXY==='true'?String(req.headers['x-forwarded-for']||'').split(',').pop().trim():'';
 return forwarded||req.socket.remoteAddress||'unknown';}
 async function exchange(req,data){assert(/^[a-f0-9]{64}$/.test(data.token||''),'Der Login-Link ist ungültig.',400);return tx(async s=>{await rate(s,'exchange:'+ip(req),30);const token=await s.get('token',hash(data.token));assert(token&&token.expires>Date.now(),'Dieser Login-Link ist abgelaufen oder wurde bereits verwendet. Bitte einen neuen anfordern.',401);let user=await s.get('user',hash(token.email));if(!user){assert(token.company||token.email===adminEmail,'Zugang nicht vorhanden.',403);let companyId=null;if(token.company){companyId=id();await s.put('company',{...token.company,id:companyId,email:token.email,status:'pending',createdAt:new Date().toISOString(),reviewNote:''});}user={id:hash(token.email),email:token.email,name:token.company?token.company.contact:'UNFALLX Administration',role:token.email===adminEmail?'admin':'partner',companyId,active:true,verifiedAt:new Date().toISOString()};await s.put('user',user,companyId||'internal');}assert(user.active,'Der Zugang ist gesperrt.',403);if(!user.verifiedAt){user.verifiedAt=new Date().toISOString();await s.put('user',user,user.companyId||'internal');}await s.remove('token',token.id);const secret=random(),session={id:hash(secret),userId:user.id,csrf:random(),createdAt:new Date().toISOString(),expires:Date.now()+12*hour};await s.put('session',session,user.id);return {cookie:sessionCookie(secret),redirect:user.role==='partner'?'/portal':'/gutachter-portal'};});}
 async function invite(user,data,resend=false){
  assert(mail.ready,'Der E-Mail-Versand ist gerade nicht eingerichtet.',503);
  const delivery=await tx(async s=>{await rate(s,'team-invite:'+user.id,20);let member;
   if(resend){member=await s.get('user',text(data.id,128,true));assert(member&&member.role==='appraiser'&&member.active,'Aktiver interner Zugang nicht gefunden.',404);}
   else{const address=email(data.email);assert(!await s.get('user',hash(address)),'Diese E-Mail-Adresse besitzt bereits einen Zugang.');member={id:hash(address),email:address,name:text(data.name,120,true),role:'appraiser',active:true,companyId:null,invitedBy:user.id,invitedAt:new Date().toISOString()};}
   for(const old of await s.list('token',member.email))if(old.purpose==='invitation')await s.remove('token',old.id);
   const token=random();await s.put('token',{id:hash(token),email:member.email,purpose:'invitation',expires:Date.now()+24*hour},member.email);member.invitationStatus='sending';await s.put('user',member,'internal');return {member,token};
  });
  try{const content=accessEmail({kind:'invitation',name:delivery.member.name,url:origin+'/login#token='+delivery.token,origin});await mail.send(delivery.member.email,content.subject,content.text,[],content.html);await tx(async s=>{const member=await s.get('user',delivery.member.id);member.invitationStatus='sent';member.invitationSentAt=new Date().toISOString();await s.put('user',member,'internal');});return {invitationSent:true,message:'Zugang angelegt. Die persönliche Einladung wurde per E-Mail versandt und ist 24 Stunden gültig.'};}
  catch{await tx(async s=>{await s.remove('token',hash(delivery.token));const member=await s.get('user',delivery.member.id);member.invitationStatus='failed';await s.put('user',member,'internal');});return {invitationSent:false,message:'Der Zugang ist angelegt, aber die Einladung konnte nicht versandt werden. Bitte „Einladung erneut senden“ verwenden.'};}
 }
 async function upload(req,user,cid){const kind=text(req.headers['x-file-kind'],30,true);assert(['photo','document','report','partner_invoice'].includes(kind),'Ungültige Dateiart.');let name;try{name=decodeURIComponent(req.headers['x-file-name']||'');}catch{throw new Problem(400,'Ungültiger Dateiname.');}name=text(name,180,true).replace(/[\/\\\r\n"<>]/g,'_');const bytes=await body(req,6*1024*1024,true);assert(bytes.length>0,'Die Datei ist leer.');const type=String(req.headers['content-type']||'').split(';')[0];let ext;
 if(['image/jpeg','image/png','image/webp'].includes(type)){try{const meta=await sharp(bytes,{limitInputPixels:60000000}).metadata();const expected={'image/jpeg':'jpeg','image/png':'png','image/webp':'webp'}[type];assert(meta.format===expected&&meta.width>0&&meta.height>0&&!meta.pages,'Ungültiges oder animiertes Bild.');await sharp(bytes,{limitInputPixels:60000000}).resize(1,1).toBuffer();ext=expected==='jpeg'?'jpg':expected;}catch{throw new Problem(400,'Dieses Bild kann nicht gelesen werden. Bitte JPG, PNG oder WebP verwenden.');}}else if(type==='application/pdf'&&bytes.subarray(0,5).toString()==='%PDF-'&&bytes.subarray(-2048).includes(Buffer.from('%%EOF'))){ext='pdf';}else throw new Problem(415,'Erlaubt sind JPG, PNG, WebP und PDF.');assert(kind!=='photo'||ext!=='pdf','Für Schadenfotos bitte ein Bild hochladen.');assert(!['report','partner_invoice'].includes(kind)||ext==='pdf','Gutachten und Rechnungen bitte als PDF hochladen.');
 return tx(async s=>{const c=await caseAccess(s,user,cid);assert(c.status!=='closed'&&c.status!=='declined','Dieser Fall ist abgeschlossen.');if(user.role==='partner'){const co=await s.get('company',user.companyId);assert(co.status==='approved','Die Firma muss zuerst freigeschaltet werden.',403);assert(kind!=='report','Gutachten können nur intern hochgeladen werden.',403);if(kind==='partner_invoice'){assert(D.payable(c)&&c.finance.partnerAcceptedAt,'Eine Rechnung ist erst nach bestätigter Vergütung und vollständigem Zahlungseingang möglich.');assert(!c.finance.partnerInvoiceId,'Eine Partnerrechnung liegt bereits vor.');}else assert(['draft','needs_info'].includes(c.status),'Weitere Unterlagen bitte im Rahmen einer Rückfrage hochladen.');}else assert(kind!=='partner_invoice','Die Partnerrechnung muss vom Partner eingereicht werden.');
 const files=await s.list('file',cid);assert(files.length<60&&files.reduce((n,f)=>n+f.size,0)+bytes.length<=180*1024*1024,'Das Upload-Limit dieses Falls ist erreicht.');const usage=await s.get('system','storage')||{id:'storage',bytes:0};assert(usage.bytes+bytes.length<=Number(env.PORTAL_STORAGE_MB||750)*1024*1024,'Der verfügbare Dokumentenspeicher ist belegt. Bitte UNFALLX kontaktieren.',507);const file={id:id(),caseId:cid,kind,name:name.replace(/\.[^.]+$/,'')+'.'+ext,type,size:bytes.length,sha256:hash(bytes),at:new Date().toISOString(),by:user.name};await s.blob(file.id,bytes);await s.put('file',file,cid);usage.bytes+=bytes.length;await s.put('system',usage);if(kind==='partner_invoice'){c.finance.partnerInvoiceId=file.id;c.finance.partnerInvoiceApproved=false;}await audit(s,user,c,'Datei hochgeladen',file.name);return {file};});}
 async function action(s,user,c,data){assert(data.version===c.version,'Der Fall wurde inzwischen geändert. Bitte neu laden.',409);const a=data.action;
 if(a==='save'){assert(user.role!=='partner'||['draft','needs_info'].includes(c.status),'Der eingereichte Fall ist schreibgeschützt.',403);c.intake=D.intake(data);await audit(s,user,c,'Falldaten aktualisiert');}
 else if(a==='submit'){assert(user.role==='partner','Diese Aktion ist für Partner vorgesehen.',403);const co=await s.get('company',user.companyId);assert(co.status==='approved','Deine Firma ist noch nicht freigeschaltet.',403);assert(['draft','needs_info'].includes(c.status),'Der Fall wurde bereits eingereicht.');assert(c.intake.authority,'Bitte die Berechtigung zur Datenübermittlung bestätigen.');assert((await s.list('file',c.id)).some(f=>f.kind==='photo'),'Bitte mindestens ein Schadenfoto hochladen.');c.status='submitted';await audit(s,user,c,'Fall eingereicht');}
 else if(a==='comment'){const note=text(data.note,4000,true);await audit(s,user,c,'Nachricht',note);}
 else if(a==='accept_terms'){assert(user.role==='partner'&&c.finance&&c.finance.agreement&&c.finance.partnerNet>0,'Es liegt noch keine Vergütungsvereinbarung vor.');c.finance.partnerAcceptedAt=new Date().toISOString();await audit(s,user,c,'Vergütung vom Partner bestätigt',c.finance.agreement);}
 else {assert(user.role!=='partner','Nur das UNFALLX-Team darf diese Aktion ausführen.',403);
 if(a==='status'){const status=text(data.status,30,true);assert((D.transitions[c.status]||[]).includes(status),'Dieser Statuswechsel ist nicht möglich.');if(status==='needs_info')assert(text(data.note,4000,true),'Bitte die Rückfrage beschreiben.');if(status==='report_ready')assert((await s.list('file',c.id)).some(f=>f.kind==='report'),'Bitte zuerst das fertige Gutachten als PDF hochladen.');if(status==='report_sent')assert(data.confirmed===true&&text(data.reference,300,true),'Bitte Versand mit Empfänger und Versanddatum dokumentieren.');if(status==='closed')assert(!c.finance?.partnerNet||c.finance.paidOutAt,'Bitte erst die Partnerabrechnung abschließen.');c.status=status;await audit(s,user,c,'Status: '+D.caseStates[status],text(data.note||data.reference,4000));}
 else if(a==='assign'){isAdmin(user);const member=await s.get('user',text(data.assignee,128,true));assert(member&&member.active&&['admin','appraiser'].includes(member.role),'Bitte einen aktiven internen Bearbeiter auswählen.');c.assignee=member.id;await audit(s,user,c,'Bearbeiter zugewiesen',member.name,true);}
 else if(a==='finance'){isAdmin(user);assert(!c.finance?.partnerInvoiceId&&!c.finance?.paidOutAt,'Nach Eingang der Partnerrechnung sind die vereinbarten Beträge gesperrt.');const old=c.finance||{};const net=D.money(data.invoiceNet),gross=D.money(data.invoiceGross),partner=D.money(data.partnerNet);assert(gross>=net&&net>0&&partner<=net,'Bitte plausible Gutachten- und Partnerbeträge eingeben.');const agreement=text(data.agreement,1000,true);c.finance={...old,invoiceNet:net,invoiceGross:gross,invoiceNumber:text(data.invoiceNumber,100,true),partnerNet:partner,agreement,agreedAt:new Date().toISOString(),received:old.received||0,partnerAcceptedAt:old.partnerNet===partner&&old.agreement===agreement?old.partnerAcceptedAt:null};assert(c.finance.received<=gross,'Bereits erfasste Zahlung übersteigt den Rechnungsbetrag.');await audit(s,user,c,'Vergütung zur Bestätigung hinterlegt',agreement);}
 else if(a==='payment'){isAdmin(user);assert(c.finance?.invoiceGross&&!c.finance.paidOutAt,'Bitte zuerst die Rechnungsdaten erfassen.');const cents=D.money(data.amount);assert(cents>0&&c.finance.received+cents<=c.finance.invoiceGross,'Zahlung übersteigt den offenen Rechnungsbetrag.');const reference=text(data.reference,300,true);const paidDate=D.date(data.date);c.finance.received+=cents;await s.put('payment',{id:id(),caseId:c.id,cents,date:paidDate,reference,actor:user.name,at:new Date().toISOString()},c.id);await audit(s,user,c,'Zahlungseingang erfasst',reference,true);}
 else if(a==='approve_invoice'){isAdmin(user);assert(D.payable(c)&&c.finance.partnerAcceptedAt&&c.finance.partnerInvoiceId,'Die Partnerrechnung ist noch nicht freigabefähig.');assert(data.confirmed===true,'Bitte die Rechnungsprüfung bestätigen.');c.finance.partnerInvoiceApproved=true;c.finance.approvedBy=user.id;await audit(s,user,c,'Partnerrechnung freigegeben');}
 else if(a==='payout'){isAdmin(user);assert(D.payable(c)&&c.finance.partnerInvoiceApproved&&!c.finance.paidOutAt,'Die Auszahlung ist noch nicht freigegeben oder bereits erfasst.');assert(data.confirmed===true,'Bitte die erfolgte Banküberweisung bestätigen.');c.finance.paidOutAt=D.date(data.date);c.finance.payoutReference=text(data.reference,300,true);await audit(s,user,c,'Auszahlung erfasst',c.finance.payoutReference);}
 else if(a==='internal_note'){c.internalNote=text(data.note,8000);await audit(s,user,c,'Interne Notiz aktualisiert','',true);}
 else throw new Problem(400,'Unbekannte Aktion.');
 }return {case:D.publicCase(c,user)};}
 async function dispatch(req,user,cid,data){assert(user.role!=='partner','Nur UNFALLX kann Dokumente versenden.',403);assert(data.confirmed===true,'Bitte den Versand bestätigen.');let payload;await tx(async s=>{const c=await caseAccess(s,user,cid);assert(c.version===data.version,'Fall geändert. Bitte neu laden.',409);assert(c.status==='report_ready'&&c.intake.shareWithLawyer&&c.intake.lawyerEmail,'Bitte Gutachten freigeben und eine autorisierte Kanzlei hinterlegen.');assert(!c.dispatch||c.dispatch.state==='failed','Dieser Versand wurde bereits ausgelöst.');const file=await s.get('file',text(data.fileId,128,true));assert(file&&file.caseId===cid&&file.kind==='report','Gutachten nicht gefunden.');payload={to:c.intake.lawyerEmail,name:file.name,bytes:await s.blob(file.id),number:c.number};c.dispatch={state:'sending',at:new Date().toISOString()};await audit(s,user,c,'Kanzleiversand gestartet',payload.to,true);});
 try{await mail.send(payload.to,'UNFALLX Gutachten · '+payload.number,`Guten Tag,\n\nanbei erhalten Sie das freigegebene Gutachten zum Vorgang ${payload.number} im Rahmen des vorliegenden Auftrags.\n\nFür Rückfragen: info@unfallx.com\nUNFALLX · Unext GmbH`,[{filename:payload.name,content:payload.bytes,contentType:'application/pdf'}]);}catch{await tx(async s=>{const c=await caseAccess(s,user,cid);c.dispatch.state='failed';await audit(s,user,c,'Kanzleiversand fehlgeschlagen','Bitte Empfänger prüfen und erneut versuchen.',true);});throw new Problem(503,'Die E-Mail konnte nicht bestätigt werden. Bitte den Versandstatus vor einem erneuten Versand prüfen.');}
 return tx(async s=>{const c=await caseAccess(s,user,cid);c.dispatch={state:'sent',at:new Date().toISOString(),to:payload.to};c.status='report_sent';await audit(s,user,c,'Gutachten an Kanzlei versandt');return {case:D.publicCase(c,user)};});}
 async function route(req,res,url){
 if(req.method==='POST')assert(req.headers.origin===origin,'Anfrageherkunft nicht erlaubt.',403);
 assert(['GET','POST'].includes(req.method),'Methode nicht erlaubt.',405);
 const path=url.pathname.replace('/api/portal','');
 if(path==='/login'&&req.method==='POST')return loginRequest(req,await body(req),false);
 if(path==='/register'&&req.method==='POST')return loginRequest(req,await body(req),true);
 if(path==='/exchange'&&req.method==='POST'){const result=await exchange(req,await body(req));res.setHeader('Set-Cookie',result.cookie);delete result.cookie;return result;}
 const {user,session}=await tx(s=>auth(req,s));
 if(path==='/me'&&req.method==='GET')return tx(async s=>({user,csrf:session.csrf,company:user.companyId?await s.get('company',user.companyId):null,states:D.caseStates}));
 if(path==='/logout'&&req.method==='POST'){await tx(s=>s.remove('session',session.id));res.setHeader('Set-Cookie',sessionCookie('',0));return {ok:true};}
 if(path==='/settings'&&req.method==='GET')return tx(async s=>({profile:{name:user.name,phone:user.phone||'',jobTitle:user.jobTitle||'',email:user.email},preferences:user.preferences||{startPage:'start',compact:false,reducedMotion:false,theme:'light'},activeSessions:(await s.list('session',user.id)).filter(x=>x.expires>Date.now()).length,storage:user.role==='admin'?{used:(await s.get('system','storage'))?.bytes||0,limit:Number(env.PORTAL_STORAGE_MB||750)*1024*1024}:null}));
 if(path==='/settings'&&req.method==='POST'){const data=await body(req);return tx(async s=>{const fresh=await s.get('user',user.id);const name=text(data.name,120,true),phone=text(data.phone,40),jobTitle=text(data.jobTitle,100);assert(['start','faelle'].includes(data.startPage),'Bitte eine gültige Startansicht wählen.');assert(typeof data.compact==='boolean'&&typeof data.reducedMotion==='boolean','Ungültige Anzeigeeinstellung.');assert(['light','dark'].includes(data.theme),'Bitte eine gültige Darstellung wählen.');fresh.name=name;fresh.phone=phone;fresh.jobTitle=jobTitle;fresh.preferences={startPage:data.startPage,compact:data.compact,reducedMotion:data.reducedMotion,theme:data.theme};await s.put('user',fresh,fresh.companyId||'internal');return {user:fresh,message:'Deine Einstellungen wurden gespeichert.'};});}
 if(path==='/sessions/revoke-others'&&req.method==='POST'){const data=await body(req);assert(data.confirmed===true,'Bitte Abmeldung der anderen Geräte bestätigen.');return tx(async s=>{let count=0;for(const other of await s.list('session',user.id))if(other.id!==session.id){await s.remove('session',other.id);count++;}return {message:'Andere Sitzungen wurden abgemeldet.',revoked:count};});}
 if(path==='/cases'&&req.method==='GET')return tx(async s=>({cases:(await s.list('case',user.role==='partner'?user.companyId:undefined)).filter(c=>user.role!=='appraiser'||c.assignee===user.id).map(c=>D.publicCase(c,user))}));
 if(path==='/cases'&&req.method==='POST'){const data=await body(req);return tx(async s=>{assert(user.role==='partner','Neue Fälle werden vom Partner eingereicht.',403);const co=await s.get('company',user.companyId);assert(co.status==='approved','Deine Firma ist noch nicht freigeschaltet.',403);await rate(s,'new-case:'+user.companyId,25,24*hour);const c={id:id(),number:'UX-'+new Date().getUTCFullYear()+'-'+random().slice(0,8).toUpperCase(),companyId:user.companyId,companyName:co.name,status:'draft',version:0,intake:D.intake(data),assignee:null,createdAt:new Date().toISOString(),finance:null};await audit(s,user,c,'Fall angelegt');return {case:D.publicCase(c,user)};});}
 let m=path.match(/^\/cases\/([a-f0-9-]{36})(\/files|\/dispatch)?$/);
 if(m){const cid=m[1];if(m[2]==='/files'&&req.method==='POST')return upload(req,user,cid);if(m[2]==='/dispatch'&&req.method==='POST')return dispatch(req,user,cid,await body(req));if(!m[2]&&req.method==='POST'){const data=await body(req);return tx(async s=>action(s,user,await caseAccess(s,user,cid),data));}if(!m[2]&&req.method==='GET')return tx(async s=>{const c=await caseAccess(s,user,cid);return {case:D.publicCase(c,user),files:(await s.list('file',cid)).filter(f=>(user.role!=='appraiser'||f.kind!=='partner_invoice')&&(user.role!=='partner'||f.kind!=='report'||['report_ready','report_sent','closed'].includes(c.status))),events:(await s.list('event',cid)).filter(e=>user.role!=='partner'||!e.internal).sort((a,b)=>a.at.localeCompare(b.at)),payments:user.role==='admin'?await s.list('payment',cid):[]};});}
 m=path.match(/^\/files\/([a-f0-9-]{36})$/);if(m&&req.method==='GET'){const result=await tx(async s=>{const f=await s.get('file',m[1]);assert(f,'Datei nicht gefunden.',404);const c=await caseAccess(s,user,f.caseId);assert(user.role!=='appraiser'||f.kind!=='partner_invoice','Datei nicht gefunden.',404);assert(user.role!=='partner'||f.kind!=='report'||['report_ready','report_sent','closed'].includes(c.status),'Gutachten noch nicht freigegeben.',403);return {file:f,bytes:await s.blob(f.id)};});assert(result.bytes,'Datei nicht gefunden.',404);res.writeHead(200,{'Content-Type':result.file.type,'Content-Disposition':`attachment; filename="UNFALLX-${result.file.id}.${result.file.type==='application/pdf'?'pdf':result.file.type.split('/')[1]}"; filename*=UTF-8''${encodeURIComponent(result.file.name)}`,'Content-Length':result.bytes.length,'Content-Security-Policy':"default-src 'none'; sandbox"});res.end(result.bytes);return null;}
 if(path==='/profile'&&req.method==='POST'){const data=await body(req);return tx(async s=>{assert(user.role==='partner','Nur für Firmenkonten.',403);const co=await s.get('company',user.companyId);co.request=text(data.request,4000,true);co.requestedAt=new Date().toISOString();await s.put('company',co);return {message:'Deine Anfrage wurde an die Administration übermittelt.'};});}
 if(path==='/export'&&req.method==='GET')return tx(async s=>({exportedAt:new Date().toISOString(),user,company:user.companyId?await s.get('company',user.companyId):null,cases:(await s.list('case',user.role==='partner'?user.companyId:undefined)).filter(c=>user.role!=='appraiser'||c.assignee===user.id).map(c=>D.publicCase(c,user))}));
 if(path.startsWith('/admin/')){isAdmin(user);
 if(path==='/admin/overview'&&req.method==='GET')return tx(async s=>({companies:await s.list('company'),team:(await s.list('user')).filter(u=>u.role!=='partner'),storage:await s.get('system','storage')}));
 if(path==='/admin/company'&&req.method==='POST'){const data=await body(req);return tx(async s=>{const co=await s.get('company',text(data.id,128,true));assert(co,'Firma nicht gefunden.',404);assert(['approved','rejected','suspended','pending'].includes(data.status),'Ungültiger Status.');co.status=data.status;co.reviewNote=text(data.note,2000);co.reviewedBy=user.id;co.reviewedAt=new Date().toISOString();await s.put('company',co);await s.put('admin_event',{id:id(),action:'Firma '+co.name+': '+co.status,actor:user.id,at:co.reviewedAt});return {company:co};});}
 if(path==='/admin/invite'&&req.method==='POST')return invite(user,await body(req));
 if(path==='/admin/resend-invitation'&&req.method==='POST')return invite(user,await body(req),true);
 if(path==='/admin/team'&&req.method==='POST'){const data=await body(req);return tx(async s=>{const member=await s.get('user',text(data.id,128,true));assert(member&&member.role==='appraiser','Nur interne Mitarbeiterzugänge können hier gesperrt werden.');member.active=data.active===true;await s.put('user',member,'internal');for(const session of await s.list('session',member.id))await s.remove('session',session.id);return {ok:true};});}
 }
 throw new Problem(404,'Nicht gefunden.');
 }
 async function handle(req,res,headers){for(const [k,v]of Object.entries(headers))res.setHeader(k,v);res.setHeader('Cache-Control','private, no-store, max-age=0');res.setHeader('Pragma','no-cache');res.setHeader('Referrer-Policy','no-referrer');res.setHeader('X-Robots-Tag','noindex, nofollow');try{const result=await route(req,res,new URL(req.url,origin));if(result!==null){res.setHeader('Content-Type','application/json; charset=utf-8');res.end(JSON.stringify(result));}}catch(e){if(!res.headersSent){res.statusCode=e.status||500;res.setHeader('Content-Type','application/json; charset=utf-8');res.end(JSON.stringify({error:e.status?e.message:'Die Aktion konnte nicht gespeichert werden. Bitte erneut versuchen.'}));}else res.end();if(!e.status)console.error('Portal request failed:',e.code||e.name);}}
 const cleanupTimer=setInterval(()=>{if(database)tx(cleanup).catch(()=>{});},hour);cleanupTimer.unref();
 return {handle,status:()=>({database:database?'ready':'pending',mail:mail.ready}),ready:db,close:async()=>{clearInterval(cleanupTimer);if(database)await database.close();}};
}
module.exports={createPortal};
