'use strict';
const path=require('node:path');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const logo='<img src="cid:unfallx-logo" width="186" alt="UNFALLX" style="display:block;width:186px;max-width:100%;height:auto;border:0">';
// Every transactional email shares one fluid frame and an embedded, offline-readable logo.
function emailFrame({content,title='UNFALLX Connect',preheader='',origin='https://unfallx.com'}){
 return `<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title></head><body style="margin:0;padding:0;background:#f3f4f6;font-family:Arial,Helvetica,sans-serif;color:#475467"><div style="display:none;max-height:0;overflow:hidden;mso-hide:all">${esc(preheader)}</div><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#f3f4f6"><tr><td align="center" style="padding:24px 12px"><table data-unfallx-email="v2" role="presentation" width="600" cellpadding="0" cellspacing="0" style="width:100%;max-width:600px;background:#ffffff;border:1px solid #e4e7ec;border-radius:24px;overflow:hidden"><tr><td style="padding:28px 24px;border-bottom:3px solid #e3241c">${logo}<p style="margin:12px 0 0;font-size:10px;letter-spacing:2px;color:#667085">CONNECT · DEIN DIGITALER ARBEITSPLATZ</p></td></tr><tr><td style="padding:28px 24px;font-size:15px;line-height:1.7;overflow-wrap:anywhere">${content}</td></tr><tr><td style="padding:22px 24px;background:#f9fafb;border-top:1px solid #eaecf0"><strong style="color:#17212f;font-size:14px">Wir sind für dich da.</strong><p style="margin:8px 0 0;font-size:13px;line-height:1.8"><a style="color:#b51b15" href="mailto:info@unfallx.com">info@unfallx.com</a> · <a style="color:#475467" href="tel:+4917664365185">0176 64 365 185</a><br><a href="${esc(origin)}/app-hilfe" style="color:#475467">Hilfe &amp; Anleitung</a></p></td></tr></table><p style="margin:20px 0 0;font-size:11px;color:#667085;line-height:1.9;text-align:center">UNFALLX · Unext GmbH<br>Emmentaler Str. 76E · 13407 Berlin<br><a href="${esc(origin)}/impressum" style="color:#667085">Impressum</a> &nbsp;·&nbsp; <a href="${esc(origin)}/portal-datenschutz" style="color:#667085">Datenschutz</a></p></td></tr></table></body></html>`;
}
function mailButton(url,label){return `<table role="presentation" cellpadding="0" cellspacing="0" style="margin:24px 0"><tr><td style="background:#e3241c;border-radius:14px"><a href="${esc(url)}" style="display:inline-block;padding:15px 23px;font-size:15px;line-height:1.5;font-weight:bold;text-decoration:none;color:#ffffff">${esc(label)} &rarr;</a></td></tr></table>`;}
function linkFallback(url){return `<p style="font-size:11px;line-height:1.7;color:#667085;margin:22px 0 0;word-break:break-all;overflow-wrap:anywhere">Button funktioniert nicht? Öffne diesen vollständigen Link:<br><a href="${esc(url)}" style="color:#475467">${esc(url)}</a></p>`;}
function brandHtml(html,text=''){
 if(html?.includes('data-unfallx-email="v2"'))return html;
 const fragment=html?html.replace(/^[\s\S]*?<body[^>]*>/i,'').replace(/<\/body>[\s\S]*$/i,''): `<p style="margin:0;line-height:1.8">${esc(text).replace(/\n/g,'<br>')}</p>`;
 return emailFrame({content:fragment});
}
const logoAttachment=()=>({filename:'unfallx-logo.png',path:path.join(__dirname,'../assets/email-logo.png'),cid:'unfallx-logo',contentType:'image/png',contentDisposition:'inline'});
function notice({title,copy,url,cta='App öffnen',secondary=null,origin='https://unfallx.com'}){
 const text=title+'\n\n'+copy+'\n\n'+cta+': '+url+(secondary?'\n\n'+secondary.label+': '+secondary.url:'')+'\n\nUNFALLX · Unext GmbH\nEmmentaler Str. 76E, 13407 Berlin\ninfo@unfallx.com · 0176 64 365 185\nDatenschutz: '+origin+'/portal-datenschutz';
 const content=`<h1 style="font-size:28px;line-height:1.25;letter-spacing:-.7px;color:#17212f;margin:0 0 20px">${esc(title)}</h1><p style="margin:0;font-size:15px;line-height:1.8">${esc(copy).replace(/\n/g,'<br>')}</p>${mailButton(url,cta)}${secondary?`<p style="font-size:12px"><a href="${esc(secondary.url)}" style="color:#475467">${esc(secondary.label)}</a></p>`:''}${linkFallback(url)}`;
 return {subject:'UNFALLX · '+title,text,html:emailFrame({title,content,preheader:title,origin})};
}
module.exports={esc,brandHtml,emailFrame,mailButton,linkFallback,logoAttachment,notice};
