'use strict';
const D=require('./domain'),sharp=require('sharp');const {storageConfig}=require('./file-storage');
function createContacts({tx,blobs,notifications,env,rate,refreshUser}){
 const recipient='info@unfallx.com';
 async function enqueue(s,c){await notifications.queue(s,{key:'contact:'+c.id,to:recipient,contactId:c.id,title:'Neue Kontaktanfrage bei UNFALLX',copy:'Eine Website-Anfrage wurde dauerhaft im geschützten Adminbereich gespeichert. Dort findest du Kontaktdaten, Nachricht und erfolgreich hochgeladene Anhänge.'+(c.attachmentErrors?' Nicht alle Anhänge konnten gespeichert werden. Bitte mit der anfragenden Person klären.':''),url:'https://admin.unfallx.com/gutachter-portal#kontakte',cta:'Kontaktanfragen öffnen'});}
 const response=c=>({ok:true,delivery:'queued',reference:c.id,attachmentErrors:c.attachmentErrors||0,message:c.attachmentErrors?'Ihre Nachricht wurde gespeichert. Nicht alle Fotos konnten übernommen werden. Bitte nennen Sie bei Rückfragen die angezeigte Referenz.':'Ihre Nachricht wurde sicher gespeichert. UNFALLX bearbeitet Ihre Anfrage.'});
 async function submit(data,meta){
  const {fotos=[],...details}=data;D.assert(fotos.length<=3,'Maximal drei Fotos.',413);
  // Decode before any object is accepted, not just its file signature.
  for(const f of fotos){try{const m=await sharp(f.buf,{limitInputPixels:60000000}).metadata();D.assert(({jpeg:'image/jpeg',png:'image/png',webp:'image/webp'})[m.format]===f.typ&&!m.pages);await sharp(f.buf,{limitInputPixels:60000000}).resize(1,1).toBuffer();}catch{throw new D.Problem(415,'Ein Foto ist nicht lesbar. Bitte JPG, PNG oder WebP verwenden.');}}
  const key=D.hash(JSON.stringify([details,fotos.map(f=>D.hash(f.buf)),Math.floor(Date.now()/600000)]));
  const c=await tx(async s=>{const prev=await s.get('contact_dedupe',key),existing=prev&&await s.get('contact_request',prev.contactId);if(existing)return {...existing,repeated:true};await rate(s,'contact:'+D.hash(meta.ip||'unknown'),8,600000);const row={id:D.id(),details,files:[],state:'new',intakeState:'receiving',expectedAttachments:fotos.length,attachmentErrors:0,createdAt:new Date().toISOString(),leaseUntil:Date.now()+10*60000,version:1};await s.put('contact_request',row);await s.put('contact_dedupe',{id:key,contactId:row.id,expires:Date.now()+3600000});return row;});
  if(c.repeated)return response(c);
  let failures=0;
  for(const f of fotos)try{
   const prepare=async s=>{const current=await s.get('contact_request',c.id);D.assert(current?.intakeState==='receiving'&&current.leaseUntil>Date.now(),'Anfrage wurde bereits übernommen.',409);const usage=await s.get('system','storage')||{id:'storage',bytes:0};D.assert(usage.bytes+f.buf.length<=storageConfig(env).limit,'Dokumentenspeicher ist belegt.',507);return {current,usage};};await tx(prepare);
   await blobs.write(f.buf,async(s,staged)=>{const {current,usage}=await prepare(s);await staged.attach(s);const file={id:staged.id,contactId:c.id,name:f.name,type:f.typ,size:f.buf.length,sha256:D.hash(f.buf)};await s.put('contact_file',file,c.id);current.files.push(file.id);await s.put('contact_request',current);usage.bytes+=f.buf.length;await s.put('system',usage);});
  }catch{failures++;}
  const saved=await tx(async s=>{const current=await s.get('contact_request',c.id);current.intakeState='stored';current.attachmentErrors=Math.max(failures,current.expectedAttachments-current.files.length);delete current.leaseUntil;current.version++;await s.put('contact_request',current);await enqueue(s,current);return current;});void notifications.flush();return response(saved);
 }
 async function recover(){await tx(async s=>{for(const c of (await s.list('contact_request')).filter(c=>c.intakeState==='receiving'&&c.leaseUntil<Date.now())){c.intakeState='stored';c.attachmentErrors=c.expectedAttachments-c.files.length;c.version++;delete c.leaseUntil;await s.put('contact_request',c);await enqueue(s,c);}for(const d of await s.list('contact_dedupe'))if(d.expires<Date.now())await s.remove('contact_dedupe',d.id);});}
 async function overview(page=0){D.assert(Number.isInteger(page)&&page>=0&&page<=100000,'Ungültige Seite.');await recover();return tx(async s=>{const notices=await s.list('notification'),files=await s.list('contact_file'),all=(await s.list('contact_request')).sort((a,b)=>(a.state==='done')-(b.state==='done')||b.createdAt.localeCompare(a.createdAt));return {page,pages:Math.ceil(all.length/50),total:all.length,contacts:all.slice(page*50,page*50+50).map(c=>{const n=notices.find(n=>n.contactId===c.id);return {...c,files:undefined,attachments:files.filter(f=>f.contactId===c.id),notification:n?{id:n.id,state:n.state,lastError:n.lastError}:null};})};});}
 async function change(user,data){D.assert(user.role==='admin','Nur für Administration.',403);return tx(async s=>{user=await refreshUser(s,user);D.assert(user.role==='admin','Nur für Administration.',403);const c=await s.get('contact_request',D.text(data.id,128,true));D.assert(c,'Anfrage nicht gefunden.',404);D.assert(c.version===data.version,'Die Anfrage wurde geändert. Bitte neu laden.',409);D.assert(['new','in_progress','done'].includes(data.state),'Ungültiger Status.');c.state=data.state;c.note=D.text(data.note,2000);c.version++;c.updatedAt=new Date().toISOString();c.updatedBy=user.id;await s.put('contact_request',c);return {message:'Kontaktanfrage aktualisiert.'};});}
 async function download(user,id){let file;const bytes=await blobs.read(id,async s=>{user=await refreshUser(s,user);D.assert(user.role==='admin','Nur für Administration.',403);file=await s.get('contact_file',id);D.assert(file&&await s.get('contact_request',file.contactId),'Anhang nicht gefunden.',404);});return {file,bytes};}
 return {submit,overview,change,download,recover};
}
module.exports={createContacts};
