'use strict';
const D=require('./domain');
function createDocuments({tx,body,env,rate}){
 const allowed=u=>D.assert(['admin','partner'].includes(u.role),'Dieser PDF-Bereich ist nur für Administration und Partnerbetriebe.',403);
 const visible=(u,d)=>u.role==='admin'||d.companyId===u.companyId;
 async function overview(user){allowed(user);return tx(async s=>({documents:(await s.list('vault_document')).filter(d=>!d.archivedAt&&visible(user,d)).sort((a,b)=>b.at.localeCompare(a.at)),companies:user.role==='admin'?(await s.list('company')).filter(c=>c.status==='approved').map(c=>({id:c.id,name:c.name})):[]}));}
 async function upload(req,user){allowed(user);const raw=await body(req,6*1024*1024,true);D.assert(raw.length&&String(req.headers['content-type']).split(';')[0]==='application/pdf'&&raw.subarray(0,5).toString()==='%PDF-'&&raw.subarray(-2048).includes(Buffer.from('%%EOF')),'Bitte eine PDF-Datei bis 6 MB auswählen.',415);let name;try{name=decodeURIComponent(req.headers['x-file-name']||'');}catch{throw new D.Problem(400,'Ungültiger Dateiname.');}name=D.text(name,180,true).replace(/[\/\\\r\n"<>]/g,'_');
 return tx(async s=>{await rate(s,'vault:'+user.id,30);const companyId=user.role==='partner'?user.companyId:D.text(req.headers['x-company-id'],128)||null;if(companyId)D.assert((await s.get('company',companyId))?.status==='approved','Bitte einen freigeschalteten Partner wählen.',403);const storedName=name.replace(/\.pdf$/i,'')+'.pdf',sha256=D.hash(raw);const existing=(await s.list('vault_document')).find(d=>!d.archivedAt&&d.companyId===companyId&&d.name===storedName&&d.sha256===sha256);if(existing)return {document:existing,message:'Diese PDF ist bereits sicher gespeichert.'};const usage=await s.get('system','storage')||{id:'storage',bytes:0};D.assert(usage.bytes+raw.length<=Number(env.PORTAL_STORAGE_MB||2048)*1024*1024,'Der Dokumentenspeicher ist belegt.',507);const doc={id:D.id(),companyId,name:storedName,size:raw.length,type:'application/pdf',by:user.name,at:new Date().toISOString(),sha256};await s.blob(doc.id,raw);await s.put('vault_document',doc,companyId||'internal');usage.bytes+=raw.length;await s.put('system',usage);return {document:doc,message:companyId?'PDF für diesen Partner und die Administration gespeichert.':'PDF ausschließlich für die Administration gespeichert.'};});}
 async function download(user,id){allowed(user);return tx(async s=>{const d=await s.get('vault_document',id);D.assert(d&&!d.archivedAt&&visible(user,d),'Dokument nicht gefunden.',404);return {file:d,bytes:await s.blob(d.id)};});}
 return {overview,upload,download};
}
module.exports={createDocuments};
