'use strict';
const {storageConfig}=require('./file-storage');
const D=require('./domain');
function createDocuments({tx,body,env,rate,blobs,refreshUser}){
 const allowed=u=>D.assert(['admin','partner'].includes(u.role),'Dieser PDF-Bereich ist nur für Administration und Partnerbetriebe.',403);
 const visible=(u,d)=>u.role==='admin'||d.companyId===u.companyId;
 const mutable=(user,d)=>user.role==='admin'||d.uploadedByRole==='partner'||!d.uploadedByRole&&d.by===user.name;
 async function overview(user){allowed(user);return tx(async s=>{const files=(await s.list('vault_document')).filter(d=>visible(user,d)).sort((a,b)=>b.at.localeCompare(a.at)).map(d=>({...d,canDelete:!d.archivedAt&&mutable(user,d),canRestore:!!d.archivedAt&&mutable(user,d)}));return {documents:files.filter(d=>!d.archivedAt),deletedDocuments:files.filter(d=>d.archivedAt),companies:user.role==='admin'?(await s.list('company')).filter(c=>c.status==='approved').map(c=>({id:c.id,name:c.name})):[]};});}
 async function change(user,id,data){allowed(user);return tx(async s=>{
  const d=await s.get('vault_document',id);D.assert(d&&visible(user,d),'Dokument nicht gefunden.',404);D.assert(mutable(user,d),'Dieses Dokument wird von der Administration verwaltet.',403);
  if(user.role==='partner')D.assert((await s.get('company',user.companyId))?.status==='approved','Der Betrieb ist nicht freigeschaltet.',403);
  D.assert(['delete','restore'].includes(data.action)&&data.confirmed===true,'Bitte die Dateiaktion bestätigen.');
  const restore=data.action==='restore';D.assert(restore?!!d.archivedAt:!d.archivedAt,'Die Datei wurde bereits geändert. Bitte neu laden.',409);
  if(restore){delete d.archivedAt;delete d.archivedBy;}else{d.archivedAt=new Date().toISOString();d.archivedBy=user.name;}
  await s.put('vault_document',d,d.companyId||'internal');await s.put('admin_event',{id:D.id(),action:restore?'Firmenunterlage wiederhergestellt':'Firmenunterlage entfernt',documentId:d.id,companyId:d.companyId,actor:user.id,at:new Date().toISOString()});
  return {message:restore?'Dokument wiederhergestellt.':'Dokument im Papierkorb. Es kann wiederhergestellt werden.'};
 });}
 async function upload(req,user){allowed(user);const raw=await body(req,6*1024*1024,true);D.assert(raw.length&&String(req.headers['content-type']).split(';')[0]==='application/pdf'&&raw.subarray(0,5).toString()==='%PDF-'&&raw.subarray(-2048).includes(Buffer.from('%%EOF')),'Bitte eine PDF-Datei bis 6 MB auswählen.',415);let name;try{name=decodeURIComponent(req.headers['x-file-name']||'');}catch{throw new D.Problem(400,'Ungültiger Dateiname.');}name=D.text(name,180,true).replace(/[\/\\\r\n"<>]/g,'_');
 await tx(s=>rate(s,'vault-preflight:'+user.id,30));const prepare=async s=>{user=await refreshUser(s,user);const companyId=user.role==='partner'?user.companyId:D.text(req.headers['x-company-id'],128)||null;if(companyId)D.assert((await s.get('company',companyId))?.status==='approved','Bitte einen freigeschalteten Partner wählen.',403);const storedName=name.replace(/\.pdf$/i,'')+'.pdf',sha256=D.hash(raw);const existing=(await s.list('vault_document')).find(d=>!d.archivedAt&&d.companyId===companyId&&d.name===storedName&&d.sha256===sha256);if(existing)return {existing};const usage=await s.get('system','storage')||{id:'storage',bytes:0};D.assert(usage.bytes+raw.length<=storageConfig(env).limit,'Der Dokumentenspeicher ist belegt.',507);return {companyId,storedName,sha256,usage};};const early=await tx(prepare);if(early.existing)return {document:early.existing,message:'Diese PDF ist bereits sicher gespeichert.'};return blobs.write(raw,async(s,staged)=>{const {companyId,storedName,sha256,usage,existing}=await prepare(s);if(existing)return {document:existing,message:'Diese PDF ist bereits sicher gespeichert.'};const doc={id:staged.id,companyId,name:storedName,size:raw.length,type:'application/pdf',by:user.name,uploadedBy:user.id,uploadedByRole:user.role,at:new Date().toISOString(),sha256};await staged.attach(s);await s.put('vault_document',doc,companyId||'internal');usage.bytes+=raw.length;await s.put('system',usage);return {document:doc,message:companyId?'PDF für diesen Partner und die Administration gespeichert.':'PDF ausschließlich für die Administration gespeichert.'};});}
 async function download(user,id){allowed(user);let file;const bytes=await blobs.read(id,async s=>{user=await refreshUser(s,user);const d=await s.get('vault_document',id);D.assert(d&&!d.archivedAt&&visible(user,d),'Dokument nicht gefunden.',404);file=d;});return {file,bytes};}
 return {overview,upload,download,change};
}
module.exports={createDocuments};
