'use strict';
const crypto=require('crypto');
const id=()=>crypto.randomUUID();
const hash=value=>crypto.createHash('sha256').update(value).digest('hex');
const random=()=>crypto.randomBytes(32).toString('hex');
class Problem extends Error { constructor(status,message){super(message);this.status=status;} }
const assert=(condition,message='Nicht erlaubt.',status=400)=>{if(!condition)throw new Problem(status,message);};
const text=(value,max=500,required=false)=>{assert(typeof value==='string'||value===undefined,'Ungültiges Textfeld.');const v=(value||'').trim();assert(v.length<=max&&(!required||v.length>0),'Bitte alle Pflichtfelder vollständig ausfüllen.');assert(!/[\x00-\x08\x0B\x0C\x0E-\x1F]/.test(v),'Ungültige Zeichen.');return v;};
const email=value=>{const e=text(value,254,true).toLowerCase();assert(/^[^\s@<>]+@[^\s@<>]+\.[^\s@<>]+$/.test(e),'Bitte eine gültige E-Mail-Adresse eingeben.');return e;};
const money=value=>{assert(typeof value==='string'&&/^\d{1,7}([.,]\d{1,2})?$/.test(value),'Betrag bitte als Euro mit höchstens zwei Nachkommastellen eingeben.');const [a,b='']=value.replace(',','.').split('.');return Number(a)*100+Number(b.padEnd(2,'0'));};
const date=value=>{const d=text(value,10,true);assert(/^\d{4}-\d{2}-\d{2}$/.test(d)&&!Number.isNaN(Date.parse(d))&&new Date(d).toISOString().slice(0,10)===d,'Bitte ein gültiges Datum eingeben.');return d;};
const caseStates={draft:'Entwurf',recording:'Aufnahme läuft',ready_to_submit:'Bereit zur Übermittlung',submitted:'Eingereicht',review:'In Prüfung',needs_info:'Rückfrage',accepted:'Angenommen',in_progress:'Gutachten in Arbeit',report_ready:'Gutachten freigegeben',report_sent:'Gutachten versandt',closed:'Abgeschlossen',declined:'Abgelehnt'};
const transitions={draft:['recording','ready_to_submit','submitted','review','needs_info','accepted','declined'],recording:['draft','ready_to_submit','submitted','review','needs_info','accepted','declined'],ready_to_submit:['recording','submitted','review','needs_info','accepted','declined'],submitted:['review','needs_info','accepted','declined'],review:['needs_info','accepted','declined'],needs_info:['submitted','review','accepted'],accepted:['in_progress','needs_info'],in_progress:['needs_info','report_ready'],report_ready:['in_progress','report_sent'],report_sent:['closed'],closed:[],declined:[]};
const Intake=require('../assets/case-intake');
function intake(body){
 const clean={};for(const f of Intake.fields){const v=body[f.name];if(f.type==='checkbox')clean[f.name]=v===true;else if(f.type==='multiselect'){assert(v===undefined||Array.isArray(v)&&v.length<=Object.keys(Intake.options[f.name]).length,'Ungültige Hilfsmittelauswahl.');clean[f.name]=(v||[]).map(x=>text(x,40,true));assert(clean[f.name].every(x=>Object.hasOwn(Intake.options[f.name],x)),'Ungültige Hilfsmittelauswahl.');}else{clean[f.name]=text(v,f.max);if(f.type==='select'&&clean[f.name])assert(Object.hasOwn(Intake.options[f.name],clean[f.name]),'Ungültige Auswahl: '+f.label);}}
 clean.owner=text(body.owner,400);clean.ownerContact=text(body.ownerContact,400);return Intake.normalize(clean);
}
function submissionErrors(c,files){return [...Intake.errors(c.intake),...Intake.fileErrors(files)];}
function validateSubmission(c,files){const errors=submissionErrors(c,files);if(errors.length){const error=new Problem(400,'Vor dem Einreichen fehlen Angaben oder Unterlagen: '+errors.map(e=>e.label).join(', ')+'. Bitte die Fallaufnahme ergänzen.');error.fields=errors;throw error;}}

function companyData(body){const type=text(body.type,30,true);assert(['Werkstatt','Gutachter / Fotopartner','Abschleppdienst','Sonstiges Unternehmen'].includes(type),'Bitte die Unternehmensart wählen.');return {name:text(body.company,180,true),contact:text(body.contact,120,true),type,street:text(body.street,180,true),postcode:text(body.postcode,12,true),city:text(body.city,100,true),phone:text(body.phone,40,true),taxId:text(body.taxId,40),register:text(body.register,100),privacyVersion:'2026-09-09'};}
function payable(c){const f=c.finance;return Boolean(f&&f.partnerNet>0&&f.agreement&&f.agreedAt&&f.partnerAcceptedAt&&f.invoiceGross>0&&f.received>=f.invoiceGross&&['report_sent','closed'].includes(c.status));}
function publicUser(u){const keys=['id','email','name','phone','jobTitle','role','companyId','active','verifiedAt','createdAt','invitedAt','invitationStatus','invitationSentAt','preferences','termsVersion'];const result={};for(const key of keys)if(u[key]!==undefined)result[key]=u[key];result.hasPassword=!!u.passwordHash;return result;}
function publicCase(c,user){const result=structuredClone(c);if(['partner','customer'].includes(user.role)) {delete result.referrerId;delete result.referralCode;delete result.trackingEpoch;delete result.nextTask;delete result.autoixpert;delete result.internalNote;delete result.assignee;delete result.dispatch; if(result.finance){const f=result.finance;result.finance={partnerNet:f.partnerNet,agreement:f.agreement,agreedAt:f.agreedAt,partnerAcceptedAt:f.partnerAcceptedAt,payable:payable(c),paymentStatus:f.paidOutAt?'paid_out':f.partnerInvoiceApproved?'approved':f.partnerInvoiceId?'invoice_received':payable(c)?'payable':f.agreedAt?'pending_payment':'unset',paidOutAt:f.paidOutAt||null,partnerInvoiceId:f.partnerInvoiceId||null};}}if(user.role==='customer')delete result.finance;return result;}
module.exports={id,hash,random,Problem,assert,text,email,money,date,intake,submissionErrors,validateSubmission,companyData,payable,publicCase,publicUser,caseStates,transitions};
