'use strict';
const crypto=require('crypto');
const id=()=>crypto.randomUUID();
const hash=value=>crypto.createHash('sha256').update(value).digest('hex');
const random=()=>crypto.randomBytes(32).toString('hex');
class Problem extends Error { constructor(status,message){super(message);this.status=status;} }
const assert=(condition,message='Nicht erlaubt.',status=400)=>{if(!condition)throw new Problem(status,message);};
const text=(value,max=500,required=false)=>{assert(typeof value==='string'||value===undefined,'Ungültiges Textfeld.');const v=(value||'').trim();assert(v.length<=max&&(!required||v.length>0),'Bitte alle Pflichtfelder vollständig ausfüllen.');assert(!/[\x00-\x08\x0B\x0C\x0E-\x1F]/.test(v),'Ungültige Zeichen.');return v;};
const email=value=>{const e=text(value,254,true).toLowerCase();assert(/^[^\s@<>]+@[^\s@<>]+\.[^\s@<>]+$/.test(e),'Bitte eine gültige E-Mail-Adresse eingeben.');return e;};
const money=value=>{assert(typeof value==='string'&&/^\d{1,7}([.,]\d{1,2})?$/.test(value),'Betrag bitte als Euro mit höchstens zwei Nachkommastellen eingeben.');const [a,b='']=value.replace(',','.').split('.');return Number(a)*100+Number(b.padEnd(2,'0'));};
const date=value=>{const d=text(value,10,true);assert(/^\d{4}-\d{2}-\d{2}$/.test(d)&&!Number.isNaN(Date.parse(d))&&new Date(d).toISOString().slice(0,10)===d,'Bitte ein gültiges Datum eingeben.');return d;};
const caseStates={draft:'Entwurf',submitted:'Eingereicht',review:'In Prüfung',needs_info:'Rückfrage',accepted:'Angenommen',in_progress:'Gutachten in Arbeit',report_ready:'Gutachten freigegeben',report_sent:'Gutachten versandt',closed:'Abgeschlossen',declined:'Abgelehnt'};
const transitions={submitted:['review','needs_info','accepted','declined'],review:['needs_info','accepted','declined'],needs_info:['submitted','review','accepted'],accepted:['in_progress','needs_info'],in_progress:['needs_info','report_ready'],report_ready:['in_progress','report_sent'],report_sent:['closed'],closed:[],declined:[]};
function intake(body) {return {vehicle:text(body.vehicle,120,true),plate:text(body.plate,20,true),vin:text(body.vin,17),accidentDate:date(body.accidentDate),location:text(body.location,180,true),owner:text(body.owner,180,true),ownerContact:text(body.ownerContact,200,true),description:text(body.description,8000,true),insurer:text(body.insurer,180),claimNumber:text(body.claimNumber,120),lawyerEmail:body.lawyerEmail?email(body.lawyerEmail):'',authority:body.authority===true,shareWithLawyer:body.shareWithLawyer===true};}
function companyData(body){const type=text(body.type,30,true);assert(['Werkstatt','Gutachter / Fotopartner','Abschleppdienst','Sonstiges Unternehmen'].includes(type),'Bitte die Unternehmensart wählen.');return {name:text(body.company,180,true),contact:text(body.contact,120,true),type,street:text(body.street,180,true),postcode:text(body.postcode,12,true),city:text(body.city,100,true),phone:text(body.phone,40,true),taxId:text(body.taxId,40),register:text(body.register,100),privacyVersion:'2026-09-09'};}
function payable(c){const f=c.finance;return Boolean(f&&f.partnerNet>0&&f.agreement&&f.agreedAt&&f.partnerAcceptedAt&&f.invoiceGross>0&&f.received>=f.invoiceGross&&['report_sent','closed'].includes(c.status));}
function publicCase(c,user){const result=structuredClone(c);if(user.role==='partner') {delete result.internalNote;delete result.assignee;delete result.dispatch; if(result.finance){const f=result.finance;result.finance={partnerNet:f.partnerNet,agreement:f.agreement,agreedAt:f.agreedAt,partnerAcceptedAt:f.partnerAcceptedAt,payable:payable(c),paymentStatus:f.paidOutAt?'paid_out':f.partnerInvoiceApproved?'approved':f.partnerInvoiceId?'invoice_received':payable(c)?'payable':f.agreedAt?'pending_payment':'unset',paidOutAt:f.paidOutAt||null,partnerInvoiceId:f.partnerInvoiceId||null};}}return result;}
module.exports={id,hash,random,Problem,assert,text,email,money,date,intake,companyData,payable,publicCase,caseStates,transitions};
