'use strict';
const D=require('./domain');const sharp=require('sharp');const {notice}=require('./brand-mail');
function createLawyers({tx,rate,mail,origin,body}){
 const profile=d=>({name:D.text(d.name,160,true),contact:D.text(d.contact,120,true),email:D.email(d.email),phone:D.text(d.phone,50,true),address:D.text(d.address,400),website:D.text(d.website,300)});
 const safe=p=>{const {id,name,contact,email,phone,address,logoId}=p;return {id,name,contact,email,phone,address,logoId:logoId||null};};
 async function register(req,data,ip){D.assert(data.privacy===true,'Bitte die Datenschutzhinweise bestätigen.');D.assert(mail.ready,'E-Mail-Versand vorübergehend nicht verfügbar.',503);const p=profile(data);const delivery=await tx(async s=>{await rate(s,'lawyer-register:'+ip,8);await rate(s,'lawyer-email:'+p.email,3);const existing=(await s.list('lawyer')).find(x=>x.email===p.email);if(existing?.verifiedAt)return null;const token=D.random(),record={...p,id:existing?.id||D.id(),status:'pending',version:(existing?.version||0)+1,createdAt:existing?.createdAt||new Date().toISOString()};await s.put('lawyer',record);await s.put('lawyer_token',{id:D.hash(token),lawyerId:record.id,version:record.version,expires:Date.now()+86400000},record.id);return token;});if(delivery){const e=notice({title:'Kanzleipartnerschaft bestätigen',copy:'Bitte bestätige deine E-Mail-Adresse. UNFALLX prüft anschließend deine Kanzleianfrage und meldet sich persönlich. Diese Registrierung gewährt keinen Zugriff auf Kundendaten oder Gutachten.',url:origin+'/kanzleipartner#token='+delivery,cta:'E-Mail bestätigen',origin});await mail.send(p.email,e.subject,e.text,[],e.html);}return {message:'Wenn noch keine bestätigte Anfrage besteht, erhältst du einen Bestätigungslink. Bitte auch den Spamordner prüfen.'};}
 async function verify(data,ip){D.assert(/^[a-f0-9]{64}$/.test(data.token||''),'Ungültiger Link.');return tx(async s=>{await rate(s,'lawyer-verify:'+ip,30);const t=await s.get('lawyer_token',D.hash(data.token)),p=t&&await s.get('lawyer',t.lawyerId);D.assert(t&&t.expires>Date.now()&&p&&p.version===t.version,'Link abgelaufen oder bereits verwendet.',401);p.verifiedAt=new Date().toISOString();p.version++;await s.put('lawyer',p);await s.remove('lawyer_token',t.id);return {message:'E-Mail bestätigt. UNFALLX prüft deine Kanzlei und kontaktiert dich zur Zusammenarbeit.'};});}
 async function overview(){return tx(async s=>({lawyers:(await s.list('lawyer')).sort((a,b)=>a.name.localeCompare(b.name,'de'))}));}
 async function save(user,data){return tx(async s=>{const old=data.id?await s.get('lawyer',D.text(data.id,128,true)):null;D.assert(!data.id||old,'Kanzlei nicht gefunden.',404);D.assert(!old||data.version===old.version,'Kanzlei wurde geändert. Bitte neu laden.',409);D.assert(['pending','active','archived'].includes(data.status),'Ungültiger Kanzleistatus.');const p=profile(data);D.assert(!(await s.list('lawyer')).some(x=>x.id!==old?.id&&x.email===p.email),'Diese Kanzlei-E-Mail ist bereits hinterlegt.');if(p.website)D.assert(/^https:\/\/[a-z0-9.-]+(?:\/[^\s]*)?$/i.test(p.website),'Website bitte als https-Adresse angeben.');const record={...old,...p,id:old?.id||D.id(),version:(old?.version||0)+1,status:data.status,createdAt:old?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString(),updatedBy:user.id};await s.put('lawyer',record);await s.put('admin_event',{id:D.id(),action:'Kanzlei gespeichert: '+record.name,actor:user.id,at:record.updatedAt});return {lawyer:record,message:'Kanzlei gespeichert.'};});}
 async function logo(req,user,id){const bytes=await body(req,2*1024*1024,true);let output;try{const img=sharp(bytes,{limitInputPixels:16000000}),m=await img.metadata();D.assert(['jpeg','png','webp'].includes(m.format)&&!m.pages,'Bitte JPG, PNG oder WebP verwenden.');output=await img.resize(400,200,{fit:'inside',withoutEnlargement:true}).webp({quality:88}).toBuffer();}catch{throw new D.Problem(400,'Logo nicht lesbar. Bitte JPG, PNG oder WebP bis 2 MB verwenden.');}return tx(async s=>{const p=await s.get('lawyer',id);D.assert(p,'Kanzlei nicht gefunden.',404);const lid=D.id();await s.blob(lid,output);await s.put('lawyer_logo',{id:lid,lawyerId:id,type:'image/webp',size:output.length});p.logoId=lid;p.version++;await s.put('lawyer',p);return {message:'Logo gespeichert.',lawyer:p};});}
 async function image(id){return tx(async s=>{const l=await s.get('lawyer_logo',id),p=l&&await s.get('lawyer',l.lawyerId);D.assert(l&&p&&p.status==='active','Logo nicht gefunden.',404);return s.blob(id);});}
 async function assign(s,c,data){if(!data.lawyerId){c.lawyerId=null;c.lawyerHandoff=null;return;}const p=await s.get('lawyer',D.text(data.lawyerId,128,true));D.assert(p?.status==='active','Bitte eine aktive Kanzlei auswählen.');c.lawyerId=p.id;c.intake.lawyerEmail=p.email;}
 async function snapshot(s,c){if(!c.lawyerId)return {name:'Beauftragte Kanzlei',contact:'',email:c.intake.lawyerEmail,phone:'',logoId:null};const p=await s.get('lawyer',c.lawyerId);D.assert(p?.status==='active'&&p.email===c.intake.lawyerEmail,'Die hinterlegte Kanzlei wurde geändert. Bitte erneut auswählen.');return safe(p);}
 return {register,verify,overview,save,logo,image,assign,snapshot};
}
module.exports={createLawyers};
