'use strict';
const D=require('./domain');const {notice}=require('./brand-mail');
const {assert,hash,id,random}=D;
function createNotifications({tx,mail,origin,rate,tracking,recipientOrigin=()=>origin}){
 let flushing=false;
 async function queue(s,{key,to,title,copy,url,userId=null,caseId=null,subscriptionId=null,cta='App öffnen',secondary=null}){const rid=hash(key+':'+to);if(await s.get('notification',rid))return;const content=notice({title,copy,url,origin,cta,secondary});await s.put('notification',{id:rid,to,userId,caseId,subscriptionId,...content,state:'pending',attempts:0,nextAttempt:Date.now(),createdAt:new Date().toISOString()},userId||'external');}
 async function customerInvite(s,c){if(!c.intake.notifyCustomer||!c.intake.customerEmail)return;const address=c.intake.customerEmail,key=hash(c.id+':'+address);if(await s.get('case_subscription',key))return;
  try{await rate(s,'customer-invite:'+address,4,86400000);}catch(e){if(e.status===429)return;throw e;}const token=random();await s.put('case_subscription',{id:key,caseId:c.id,email:address,verifiedAt:null,active:false,createdAt:new Date().toISOString()},c.id);await s.put('notification_token',{id:hash(token),purpose:'subscribe',subscriptionId:key,expires:Date.now()+7*86400000},key);
  await queue(s,{key:'customer-invite:'+key,to:address,cta:'E-Mail bestätigen',title:'Fallbenachrichtigungen bestätigen',copy:'Ein Auftraggeber oder UNFALLX hat diese Adresse für Statusmeldungen zu einer Schadenanfrage bei UNFALLX angegeben. Bitte bestätige nur, wenn du diese Anfrage kennst. Danach erhältst du Mitteilungen zur Bearbeitung. Ohne Bestätigung versenden wir keine Fallmeldungen. Der Link gilt sieben Tage. Wenn dir die Anfrage unbekannt ist, ignoriere diese Nachricht.',url:origin+'/benachrichtigungen#token='+token});
 }
 async function event(s,user,c,event){if(event.internal||['draft','recording','ready_to_submit'].includes(c.status))return;
  const relevant=['Fall eingereicht','Kundenaufnahme abgeschlossen'].includes(event.action)||event.action.startsWith('Status: ')||['Nachricht','Falldaten aktualisiert','Unterlagen ergänzt','Unterlagen angefordert','Rückfrage beantwortet','Rückfrage erledigt','Rückfrage erneut geöffnet','Gutachten an Kanzlei versandt'].includes(event.action);if(!relevant)return;
  await customerInvite(s,c);
  let users=(await s.list('user')).filter(u=>u.active&&u.verifiedAt&&(u.role==='partner'&&u.companyId===c.companyId||u.id===c.assignee||u.role==='admin'&&['Fall eingereicht','Kundenaufnahme abgeschlossen','Rückfrage beantwortet','Unterlagen ergänzt'].includes(event.action)));
  const seen=new Set();const title=event.action==='Nachricht'?'Neue Nachricht zu deinem Fall':'Dein Fall wurde aktualisiert';const contact=['report_sent','closed'].includes(c.status)&&c.lawyerHandoff?'\nDeine Kanzlei: '+c.lawyerHandoff.name+'\nAnsprechpartner: '+(c.lawyerHandoff.contact||c.lawyerHandoff.name)+'\nE-Mail: '+c.lawyerHandoff.email+'\nTelefon: '+(c.lawyerHandoff.phone||'Bitte per E-Mail kontaktieren'):' ';const copy=`Vorgang ${c.number}: ${D.caseStates[c.status]}.\n${event.action==='Nachricht'?'Eine neue Nachricht liegt in deinem geschützten Portal vor.':'Den aktuellen Stand und die nächsten Schritte findest du im Portal.'}\nAus Datenschutzgründen enthält diese E-Mail keine Schadenfotos oder persönlichen Falldaten.${contact}`;
  for(const u of users){if(u.preferences?.caseEmails===false||seen.has(u.email))continue;seen.add(u.email);await queue(s,{key:event.id,to:u.email,title,copy,url:recipientOrigin(u)+(u.role==='partner'?'/portal':'/gutachter-portal')+'#fall/'+c.id+(['Unterlagen angefordert','Rückfrage beantwortet','Rückfrage erneut geöffnet'].includes(event.action)?'/requests':''),userId:u.id,caseId:c.id});}
  if(c.intake.notifyCustomer&&c.intake.customerEmail&&!seen.has(c.intake.customerEmail)){const sub=await s.get('case_subscription',hash(c.id+':'+c.intake.customerEmail));if(sub?.active&&sub.verifiedAt){const token=random();await s.put('notification_token',{id:hash(token),purpose:'unsubscribe',subscriptionId:sub.id,expires:Date.now()+180*86400000},sub.id);const link=tracking?await tracking.issue(s,c,sub.email):{url:origin+'/login'};await queue(s,{key:event.id,to:sub.email,title:'Aktueller Stand deiner Schadenanfrage',copy:`Vorgang ${c.number}: ${D.caseStates[c.status]}.\nÜber deinen persönlichen Statuslink siehst du den Fortschritt. Der Link gilt 90 Tage; bitte nicht öffentlich teilen.${contact}`,url:link.url,caseId:c.id,subscriptionId:sub.id,cta:'Aktuellen Status ansehen',secondary:{label:'Statusmeldungen abbestellen',url:origin+'/benachrichtigungen#unsubscribe='+token}});}}
 }
 async function validRecipient(s,row){if(row.userId){const u=await s.get('user',row.userId);if(!u?.active||!u.verifiedAt||u.email!==row.to||u.preferences?.caseEmails===false)return false;const c=await s.get('case',row.caseId);if(!c)return false;if(u.role==='partner')return c.companyId===u.companyId&&(await s.get('company',u.companyId))?.status!=='suspended';return u.role==='admin'||u.role==='appraiser'&&c.assignee===u.id;}if(row.subscriptionId){const sub=await s.get('case_subscription',row.subscriptionId),c=await s.get('case',row.caseId);return sub?.active&&!!sub.verifiedAt&&c?.intake.notifyCustomer&&c.intake.customerEmail===sub.email;}return true;}
 async function flush(){if(flushing||!mail.ready)return;flushing=true;try{for(let i=0;i<12;i++){
   const row=await tx(async s=>{const rows=await s.list('notification');for(const old of rows)if(old.state==='sending'&&old.claimedAt<Date.now()-5*60000){old.state='uncertain';await s.put('notification',old,old.userId||'external');}const next=rows.filter(r=>r.state==='pending'&&r.nextAttempt<=Date.now()).sort((a,b)=>a.createdAt.localeCompare(b.createdAt))[0];if(!next)return null;if(!await validRecipient(s,next)){next.state='cancelled';await s.put('notification',next,next.userId||'external');return {skip:true};}next.state='sending';next.claimedAt=Date.now();next.attempts++;await s.put('notification',next,next.userId||'external');return next;});if(!row)break;if(row.skip)continue;
   let failed=false;try{await mail.send(row.to,row.subject,row.text,[],row.html,`<ux-${row.id}@unfallx.com>`);}catch{failed=true;}
   await tx(async s=>{const fresh=await s.get('notification',row.id);if(!fresh||fresh.state!=='sending')return;fresh.state=failed?'uncertain':'sent';fresh.sentAt=failed?null:new Date().toISOString();fresh.lastError=failed?'SMTP hat den Versand nicht bestätigt. Vor Wiederholung Zustellung prüfen.':null;await s.put('notification',fresh,fresh.userId||'external');});
  }}catch(e){console.error('Notification queue unavailable:',e.code||e.status||'database');}finally{flushing=false;}}
 async function verify(req,data,ip){assert(/^[a-f0-9]{64}$/.test(data.token||''),'Ungültiger Bestätigungslink.');return tx(async s=>{await rate(s,'notification-verify:'+ip,30);const t=await s.get('notification_token',hash(data.token));assert(t&&t.expires>Date.now(),'Der Link ist abgelaufen oder wurde bereits verwendet.',401);const sub=await s.get('case_subscription',t.subscriptionId),c=sub&&await s.get('case',sub.caseId);assert(sub&&c,'Vorgang nicht gefunden.',404);if(t.purpose==='subscribe'){assert(c.intake.notifyCustomer&&c.intake.customerEmail===sub.email,'Diese Benachrichtigung wurde nicht mehr angefordert.',409);sub.active=true;sub.verifiedAt=new Date().toISOString();}else sub.active=false;await s.put('case_subscription',sub,c.id);await s.remove('notification_token',t.id);const link=t.purpose==='subscribe'&&tracking?await tracking.issue(s,c,sub.email):null;return {trackingUrl:link?.url||null,message:t.purpose==='subscribe'?'Bestätigt. Du erhältst ab jetzt Statusmeldungen zu diesem Vorgang.':'Die Statusmeldungen für diesen Vorgang sind abbestellt.'};});}
 async function overview(){return tx(async s=>({notifications:(await s.list('notification')).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,150).map(({id,to,subject,state,attempts,createdAt,sentAt,lastError})=>({id,to,subject,state,attempts,createdAt,sentAt,lastError}))}));}
 async function retry(data,user){assert(data.confirmed===true,'Bitte prüfen und bestätigen, dass eine erneute E-Mail erforderlich ist.');return tx(async s=>{const r=await s.get('notification',D.text(data.id,128,true));assert(r&&r.state==='uncertain','Diese Nachricht kann nicht erneut freigegeben werden.');r.state='pending';r.nextAttempt=Date.now();await s.put('notification',r,r.userId||'external');await s.put('admin_event',{id:id(),action:'E-Mail erneut freigegeben',notificationId:r.id,actor:user.id,at:new Date().toISOString()});return {message:'Erneuter Versand freigegeben.'};});}
 return {event,queue,flush,verify,overview,retry};
}
module.exports={createNotifications};
