'use strict';
const D=require('./domain');const {assert,text,hash,random,id,money,date}=D;
function createReferrals({tx,rate,origin}){
 const external=u=>['partner','customer'].includes(u.role);
 async function attribute(s,user,code){const link=await s.get('referral_code',code);if(!link?.active||link.userId===user.id)return;const referrer=await s.get('user',link.userId);if(!referrer?.active||referrer.email===user.email||referrer.companyId&&referrer.companyId===user.companyId)return;await s.put('referral_attribution',{id:user.id,userId:user.id,companyId:user.companyId||null,referrerId:referrer.id,code,createdAt:new Date().toISOString()},referrer.id);}
 async function attach(s,c,code){if(!code)return;const ref=await s.get('referral_code',text(code,32).toUpperCase()),u=ref&&await s.get('user',ref.userId);assert(ref?.active&&u?.active&&external(u),'Empfehlungscode nicht gefunden.');assert(u.id!==c.ownerUserId&&(!u.companyId||u.companyId!==c.companyId)&&u.email!==c.intake.customerEmail,'Selbstempfehlungen sind ausgeschlossen.');assert(!await s.get('referral_reward',hash('referral:'+c.id)),'Zu diesem Fall wurde bereits eine Provision angelegt.');c.referrerId=u.id;c.referralCode=ref.id;}
 async function sync(s,c){if(!['report_sent','closed'].includes(c.status))return;let attributed;if(c.ownerUserId)attributed=await s.get('referral_attribution',c.ownerUserId);else if(c.companyId)attributed=(await s.list('referral_attribution')).find(a=>a.companyId===c.companyId);if(c.referrerId)attributed={id:'case:'+c.id,referrerId:c.referrerId};if(!attributed)return;const rid=hash('referral:'+c.id);if(await s.get('referral_reward',rid))return;await s.put('referral_reward',{id:rid,caseId:c.id,referrerId:attributed.referrerId,attributionId:attributed.id,reference:'EMP-'+random().slice(0,8).toUpperCase(),state:'review',amount:0,agreement:'',version:1,createdAt:new Date().toISOString()},attributed.referrerId);}
 const publicReward=r=>({id:r.id,reference:r.reference,state:r.state,amount:r.amount,agreement:r.agreement,version:r.version,createdAt:r.createdAt,acceptedAt:r.acceptedAt||null,paidAt:r.paidAt||null});
 async function overview(user){return tx(async s=>{assert(external(user),'Nur für Kunden und Partner.',403);const code=(await s.list('referral_code',user.id))[0],rewards=(await s.list('referral_reward',user.id)).map(publicReward),attributions=await s.list('referral_attribution',user.id);return {code:code?.active?code.id:null,url:code?.active?origin+'/empfehlen?ref='+code.id:null,referredAccounts:attributions.length,rewards,totals:{offered:rewards.filter(r=>r.state==='offered').reduce((n,r)=>n+r.amount,0),approved:rewards.filter(r=>r.state==='approved').reduce((n,r)=>n+r.amount,0),paid:rewards.filter(r=>r.state==='paid').reduce((n,r)=>n+r.amount,0)}};});}
 async function join(user,data){assert(external(user),'Nur für Kunden und Partner.',403);assert(data.accepted===true,'Bitte die Teilnahmebedingungen bestätigen.');return tx(async s=>{await rate(s,'referral-join:'+user.id,5);let code=(await s.list('referral_code',user.id))[0];if(!code){do{code={id:'UX-'+random().slice(0,12).toUpperCase(),userId:user.id,active:true,termsVersion:'2026-09-09',createdAt:new Date().toISOString()};}while(await s.get('referral_code',code.id));await s.put('referral_code',code,user.id);}return {message:'Dein persönlicher Empfehlungslink ist bereit.'};});}
 async function accept(user,data){return tx(async s=>{const r=await s.get('referral_reward',text(data.id,128,true));assert(r&&r.referrerId===user.id,'Provision nicht gefunden.',404);assert(r.version===data.version,'Die Provision wurde geändert. Bitte neu laden.',409);assert(r.state==='offered'&&data.accepted===true,'Bitte die angebotene Einzelvereinbarung bestätigen.');r.state='approved';r.acceptedAt=new Date().toISOString();r.version++;await s.put('referral_reward',r,r.referrerId);return {message:'Vereinbarung bestätigt. UNFALLX stimmt den Abrechnungsbeleg und die Auszahlung mit dir ab.'};});}
 async function adminOverview(){return tx(async s=>{const rewards=await s.list('referral_reward');return {rewards:await Promise.all(rewards.map(async r=>{const c=await s.get('case',r.caseId),u=await s.get('user',r.referrerId);return {...r,caseNumber:c?.number,caseStatus:c?.status,referrerName:u?.name,referrerEmail:u?.email,fullyPaid:!!(c?.finance?.invoiceGross&&c.finance.received>=c.finance.invoiceGross)};})),attributions:(await s.list('referral_attribution')).length};});}
 async function adminAction(user,data){return tx(async s=>{const r=await s.get('referral_reward',text(data.id,128,true));assert(r,'Provision nicht gefunden.',404);assert(r.version===data.version,'Die Provision wurde inzwischen geändert.',409);assert(r.state!=='paid','Eine bereits erfasste Auszahlung ist unveränderlich.');const c=await s.get('case',r.caseId);assert(c&&['report_sent','closed'].includes(c.status),'Das Gutachten muss abgeschlossen und versandt sein.');const a=text(data.action,20,true);
 if(a==='offer'){assert(['review','offered','rejected'].includes(r.state),'Eine bestätigte Vereinbarung kann nicht überschrieben werden.');r.amount=money(data.amount);assert(r.amount>0,'Bitte eine positive Provision eingeben.');r.agreement=text(data.agreement,2000,true);r.invoiceReference=text(data.invoiceReference,200,true);r.settledGross=money(data.settledGross);assert(r.settledGross>0&&data.paymentConfirmed===true,'Bitte vollständigen Zahlungseingang des Gutachtenhonorars bestätigen.');if(c.finance?.invoiceGross)assert(c.finance.received>=c.finance.invoiceGross&&r.settledGross===c.finance.invoiceGross,'Die erfasste Gutachtenrechnung ist noch nicht vollständig bezahlt oder der Betrag weicht ab.');r.paymentReference=text(data.paymentReference,300,true);r.state='offered';r.offeredAt=new Date().toISOString();r.offeredBy=user.id;}
 else if(a==='reject'){assert(r.state==='review'||r.state==='offered','Eine bereits bestätigte Vereinbarung kann hier nicht abgelehnt werden.');r.state='rejected';r.agreement=text(data.reason,2000,true);}
 else if(a==='paid'){assert(r.state==='approved'&&r.acceptedAt&&r.amount>0&&r.paymentReference&&data.confirmed===true,'Bitte Freigabe, Annahme und Zahlung prüfen.');if(c.finance?.invoiceGross)assert(c.finance.received>=c.finance.invoiceGross,'Die Gutachtenrechnung muss vollständig bezahlt sein.');r.payoutReference=text(data.reference,300,true);r.receiptReference=text(data.receiptReference,200,true);r.paidAt=date(data.date);assert(r.paidAt<=new Date().toISOString().slice(0,10),'Bitte ein bereits eingetretenes Zahlungsdatum wählen.');r.state='paid';r.paidBy=user.id;}
 else throw new D.Problem(400,'Unbekannte Aktion.');r.version++;await s.put('referral_reward',r,r.referrerId);await s.put('admin_event',{id:id(),action:'Empfehlungsprovision '+a,rewardId:r.id,amount:r.amount,actor:user.id,at:new Date().toISOString()});return {message:'Provision aktualisiert.'};});}
 return {attribute,attach,sync,overview,join,accept,adminOverview,adminAction};
}
module.exports={createReferrals};
